# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/pid_vco/pid_vco.srcs/sources_1/bd/pid_vco_wrapper/ip/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0.xci
# IP: The module: 'pid_vco_wrapper_redpitaya_adc_dac_clk_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/pid_vco/pid_vco.srcs/sources_1/bd/pid_vco_wrapper/ip/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pid_vco_wrapper_redpitaya_adc_dac_clk_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/bma/git/fpga_design/redpitaya/pid_vco/pid_vco.srcs/sources_1/bd/pid_vco_wrapper/ip/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0.xci
# IP: The module: 'pid_vco_wrapper_redpitaya_adc_dac_clk_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/pid_vco/pid_vco.srcs/sources_1/bd/pid_vco_wrapper/ip/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pid_vco_wrapper_redpitaya_adc_dac_clk_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
