# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/double_pid_vco_wrapper/double_pid_vco_wrapper.bd
# Block Designs: The module: 'double_pid_vco_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_ad9767_0_0/double_pid_vco_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_ad9767_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_ad9767_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_adc1_offset_0/double_pid_vco_wrapper_adc1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_adc1_offset_0 || ORIG_REF_NAME==double_pid_vco_wrapper_adc1_offset_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_axi_interconnect_0_0/double_pid_vco_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_axi_interconnect_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_xbar_0/double_pid_vco_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_xbar_0 || ORIG_REF_NAME==double_pid_vco_wrapper_xbar_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds_ampl_0/double_pid_vco_wrapper_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds_ampl_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds_ampl_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds_f0_0/double_pid_vco_wrapper_dds_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds_f0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds_f0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds_nco_0/double_pid_vco_wrapper_dds_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds_nco_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds_nco_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds_offset_0/double_pid_vco_wrapper_dds_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds_offset_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds_offset_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds_range_0/double_pid_vco_wrapper_dds_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds_range_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds_range_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_expanderReal_0_0/double_pid_vco_wrapper_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_expanderReal_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_expanderReal_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_ltc2145_0_0/double_pid_vco_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_ltc2145_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_ltc2145_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_kd_0/double_pid_vco_wrapper_pid_kd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_kd_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_kd_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_ki_0/double_pid_vco_wrapper_pid_ki_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_ki_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_ki_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_kp_0/double_pid_vco_wrapper_pid_kp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_kp_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_kp_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_rst_int_0/double_pid_vco_wrapper_pid_rst_int_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_rst_int_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_rst_int_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_setpoint_0/double_pid_vco_wrapper_pid_setpoint_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_setpoint_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_setpoint_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid_sign_0/double_pid_vco_wrapper_pid_sign_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid_sign_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid_sign_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_proc_sys_reset_0_0/double_pid_vco_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_proc_sys_reset_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_processing_system7_0_0/double_pid_vco_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_processing_system7_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_processing_system7_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_red_pitaya_pidv3_0_0/double_pid_vco_wrapper_red_pitaya_pidv3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_red_pitaya_pidv3_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_red_pitaya_pidv3_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/double_pid_vco_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_twoInMult_dds_ampl_0/double_pid_vco_wrapper_twoInMult_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_twoInMult_dds_ampl_0 || ORIG_REF_NAME==double_pid_vco_wrapper_twoInMult_dds_ampl_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_twoInMult_dds_range_0/double_pid_vco_wrapper_twoInMult_dds_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_twoInMult_dds_range_0 || ORIG_REF_NAME==double_pid_vco_wrapper_twoInMult_dds_range_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_xlconstant_0_0/double_pid_vco_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_xlconstant_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_xlconstant_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_xlconstant_1_0/double_pid_vco_wrapper_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_xlconstant_1_0 || ORIG_REF_NAME==double_pid_vco_wrapper_xlconstant_1_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_xlslice_0_0/double_pid_vco_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_xlslice_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_xlslice_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_adc1_offset_1/double_pid_vco_wrapper_adc1_offset_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_adc1_offset_1 || ORIG_REF_NAME==double_pid_vco_wrapper_adc1_offset_1}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_red_pitaya_pidv3_0_1/double_pid_vco_wrapper_red_pitaya_pidv3_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_red_pitaya_pidv3_0_1 || ORIG_REF_NAME==double_pid_vco_wrapper_red_pitaya_pidv3_0_1}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_setpoint_0/double_pid_vco_wrapper_pid1_setpoint_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_setpoint_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_setpoint_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_kp_0/double_pid_vco_wrapper_pid1_kp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_kp_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_kp_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_ki_0/double_pid_vco_wrapper_pid1_ki_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_ki_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_ki_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_sign_0/double_pid_vco_wrapper_pid1_sign_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_sign_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_sign_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_rst_int_0/double_pid_vco_wrapper_pid1_rst_int_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_rst_int_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_rst_int_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_pid1_kd_0/double_pid_vco_wrapper_pid1_kd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_pid1_kd_0 || ORIG_REF_NAME==double_pid_vco_wrapper_pid1_kd_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_twoInMult_dds1_range_0/double_pid_vco_wrapper_twoInMult_dds1_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_twoInMult_dds1_range_0 || ORIG_REF_NAME==double_pid_vco_wrapper_twoInMult_dds1_range_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds1_range_0/double_pid_vco_wrapper_dds1_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds1_range_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds1_range_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_expanderReal_0_dds1_0/double_pid_vco_wrapper_expanderReal_0_dds1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_expanderReal_0_dds1_0 || ORIG_REF_NAME==double_pid_vco_wrapper_expanderReal_0_dds1_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds1_f0_0/double_pid_vco_wrapper_dds1_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds1_f0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds1_f0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds1_nco_0/double_pid_vco_wrapper_dds1_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds1_nco_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds1_nco_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_twoInMult_dds1_ampl_0/double_pid_vco_wrapper_twoInMult_dds1_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_twoInMult_dds1_ampl_0 || ORIG_REF_NAME==double_pid_vco_wrapper_twoInMult_dds1_ampl_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds1_ampl_0/double_pid_vco_wrapper_dds1_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds1_ampl_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds1_ampl_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_xlslice_dds1_0/double_pid_vco_wrapper_xlslice_dds1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_xlslice_dds1_0 || ORIG_REF_NAME==double_pid_vco_wrapper_xlslice_dds1_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_dds1_offset_0/double_pid_vco_wrapper_dds1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_dds1_offset_0 || ORIG_REF_NAME==double_pid_vco_wrapper_dds1_offset_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_tier2_xbar_0_0/double_pid_vco_wrapper_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_tier2_xbar_0_0 || ORIG_REF_NAME==double_pid_vco_wrapper_tier2_xbar_0_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_tier2_xbar_1_0/double_pid_vco_wrapper_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_tier2_xbar_1_0 || ORIG_REF_NAME==double_pid_vco_wrapper_tier2_xbar_1_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_tier2_xbar_2_0/double_pid_vco_wrapper_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_tier2_xbar_2_0 || ORIG_REF_NAME==double_pid_vco_wrapper_tier2_xbar_2_0}]

# IP: bd/double_pid_vco_wrapper/ip/double_pid_vco_wrapper_auto_pc_0/double_pid_vco_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_pid_vco_wrapper_auto_pc_0 || ORIG_REF_NAME==double_pid_vco_wrapper_auto_pc_0}]

# XDC: bd/double_pid_vco_wrapper/double_pid_vco_wrapper_ooc.xdc
