# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/vco_only_wrapper/vco_only_wrapper.bd
# Block Designs: The module: 'vco_only_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_ad9767_0_0/vco_only_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_ad9767_0_0 || ORIG_REF_NAME==vco_only_wrapper_ad9767_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_adc1_offset_0/vco_only_wrapper_adc1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_adc1_offset_0 || ORIG_REF_NAME==vco_only_wrapper_adc1_offset_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_axi_interconnect_0_0/vco_only_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==vco_only_wrapper_axi_interconnect_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_xbar_0/vco_only_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_xbar_0 || ORIG_REF_NAME==vco_only_wrapper_xbar_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dac1_offset_0/vco_only_wrapper_dac1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dac1_offset_0 || ORIG_REF_NAME==vco_only_wrapper_dac1_offset_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dds_ampl_0/vco_only_wrapper_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dds_ampl_0 || ORIG_REF_NAME==vco_only_wrapper_dds_ampl_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dds_f0_0/vco_only_wrapper_dds_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dds_f0_0 || ORIG_REF_NAME==vco_only_wrapper_dds_f0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dds_nco_0/vco_only_wrapper_dds_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dds_nco_0 || ORIG_REF_NAME==vco_only_wrapper_dds_nco_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dds_offset_0/vco_only_wrapper_dds_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dds_offset_0 || ORIG_REF_NAME==vco_only_wrapper_dds_offset_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dupplReal_1_to_2_0_0/vco_only_wrapper_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==vco_only_wrapper_dupplReal_1_to_2_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_ltc2145_0_0/vco_only_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_ltc2145_0_0 || ORIG_REF_NAME==vco_only_wrapper_ltc2145_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_proc_sys_reset_0_0/vco_only_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==vco_only_wrapper_proc_sys_reset_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_processing_system7_0_0/vco_only_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_processing_system7_0_0 || ORIG_REF_NAME==vco_only_wrapper_processing_system7_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_redpitaya_adc_dac_clk_0_0/vco_only_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==vco_only_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_twoInMult_0_0/vco_only_wrapper_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_twoInMult_0_0 || ORIG_REF_NAME==vco_only_wrapper_twoInMult_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_xlconstant_0_0/vco_only_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_xlconstant_0_0 || ORIG_REF_NAME==vco_only_wrapper_xlconstant_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_xlslice_0_0/vco_only_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_xlslice_0_0 || ORIG_REF_NAME==vco_only_wrapper_xlslice_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_expanderReal_0_0/vco_only_wrapper_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_expanderReal_0_0 || ORIG_REF_NAME==vco_only_wrapper_expanderReal_0_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_dds_ampl_1/vco_only_wrapper_dds_ampl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_dds_ampl_1 || ORIG_REF_NAME==vco_only_wrapper_dds_ampl_1}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_twoInMult_0_1/vco_only_wrapper_twoInMult_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_twoInMult_0_1 || ORIG_REF_NAME==vco_only_wrapper_twoInMult_0_1}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_0/vco_only_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_0 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_0}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_1/vco_only_wrapper_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_1 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_1}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_2/vco_only_wrapper_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_2 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_2}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_3/vco_only_wrapper_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_3 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_3}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_4/vco_only_wrapper_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_4 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_4}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_5/vco_only_wrapper_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_5 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_5}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_6/vco_only_wrapper_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_6 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_6}]

# IP: bd/vco_only_wrapper/ip/vco_only_wrapper_auto_pc_7/vco_only_wrapper_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vco_only_wrapper_auto_pc_7 || ORIG_REF_NAME==vco_only_wrapper_auto_pc_7}]

# XDC: bd/vco_only_wrapper/vco_only_wrapper_ooc.xdc
