# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# Block Designs: bd/adc2dac_ram_offset/adc2dac_ram_offset.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset || ORIG_REF_NAME==adc2dac_ram_offset}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_processing_system7_0_0/adc2dac_ram_offset_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_processing_system7_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_processing_system7_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_proc_sys_reset_0_0/adc2dac_ram_offset_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_proc_sys_reset_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_proc_sys_reset_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_ltc2145_0_0/adc2dac_ram_offset_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_ltc2145_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_ltc2145_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_redpitaya_adc_dac_clk_0_0/adc2dac_ram_offset_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_redpitaya_adc_dac_clk_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_ad9767_0_0/adc2dac_ram_offset_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_ad9767_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_ad9767_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_data16_multi_to_ram_0_0/adc2dac_ram_offset_data16_multi_to_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_data16_multi_to_ram_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_data16_multi_to_ram_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_ps7_0_axi_periph_0/adc2dac_ram_offset_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_ps7_0_axi_periph_0 || ORIG_REF_NAME==adc2dac_ram_offset_ps7_0_axi_periph_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_dupplReal_1_to_2_0_0/adc2dac_ram_offset_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_dupplReal_1_to_2_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_dupplReal_1_to_2_0_1/adc2dac_ram_offset_dupplReal_1_to_2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_dupplReal_1_to_2_0_1 || ORIG_REF_NAME==adc2dac_ram_offset_dupplReal_1_to_2_0_1}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_expanderReal_0_0/adc2dac_ram_offset_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_expanderReal_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_expanderReal_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_expanderReal_0_1/adc2dac_ram_offset_expanderReal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_expanderReal_0_1 || ORIG_REF_NAME==adc2dac_ram_offset_expanderReal_0_1}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_add_const_0_0/adc2dac_ram_offset_add_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_add_const_0_0 || ORIG_REF_NAME==adc2dac_ram_offset_add_const_0_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_xbar_0/adc2dac_ram_offset_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_xbar_0 || ORIG_REF_NAME==adc2dac_ram_offset_xbar_0}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_add_const_0_1/adc2dac_ram_offset_add_const_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_add_const_0_1 || ORIG_REF_NAME==adc2dac_ram_offset_add_const_0_1}]

# IP: bd/adc2dac_ram_offset/ip/adc2dac_ram_offset_auto_pc_0/adc2dac_ram_offset_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==adc2dac_ram_offset_auto_pc_0 || ORIG_REF_NAME==adc2dac_ram_offset_auto_pc_0}]

# XDC: bd/adc2dac_ram_offset/adc2dac_ram_offset_ooc.xdc
