# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/dds_gnuradio_wrapper/dds_gnuradio_wrapper.bd
# Block Designs: The module: 'dds_gnuradio_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_ad9767_0_0/dds_gnuradio_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_ad9767_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_ad9767_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_0_0/dds_gnuradio_wrapper_add_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_add_const_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_add_const_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_1_0/dds_gnuradio_wrapper_add_const_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_add_const_1_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_add_const_1_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_2_0/dds_gnuradio_wrapper_add_const_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_add_const_2_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_add_const_2_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_3_0/dds_gnuradio_wrapper_add_const_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_add_const_3_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_add_const_3_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_axi_interconnect_0_0/dds_gnuradio_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_axi_interconnect_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_xbar_0/dds_gnuradio_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_xbar_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_xbar_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_data16_multi_to_ram_0_0/dds_gnuradio_wrapper_data16_multi_to_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_data16_multi_to_ram_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_data16_multi_to_ram_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_dupplReal_1_to_2_0_0/dds_gnuradio_wrapper_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_dupplReal_1_to_2_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_expanderReal_0_0/dds_gnuradio_wrapper_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_expanderReal_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_expanderReal_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_expanderReal_1_0/dds_gnuradio_wrapper_expanderReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_expanderReal_1_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_expanderReal_1_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_ltc2145_0_0/dds_gnuradio_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_ltc2145_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_ltc2145_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_nco_counter_0_0/dds_gnuradio_wrapper_nco_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_nco_counter_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_nco_counter_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_proc_sys_reset_0_0/dds_gnuradio_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_proc_sys_reset_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_processing_system7_0_0/dds_gnuradio_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_processing_system7_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_processing_system7_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_redpitaya_adc_dac_clk_0_0/dds_gnuradio_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_twoInMult_0_0/dds_gnuradio_wrapper_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_twoInMult_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_twoInMult_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_xlconstant_0_0/dds_gnuradio_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_xlconstant_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_xlconstant_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_xlslice_0_0/dds_gnuradio_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_xlslice_0_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_xlslice_0_0}]

# IP: bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_auto_pc_0/dds_gnuradio_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_gnuradio_wrapper_auto_pc_0 || ORIG_REF_NAME==dds_gnuradio_wrapper_auto_pc_0}]

# XDC: bd/dds_gnuradio_wrapper/dds_gnuradio_wrapper_ooc.xdc
