BASE_NAME=nco_fir_dac_adc
CORE_MODULES_LIST = \
	${OSCIMP_DIGITAL_DRIVER}/data_to_ram_core/data_to_ram_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/fir_core/fir_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/nco_counter_core/nco_counter_core.ko
include $(OSCIMP_DIGITAL_APP)/Makefile.inc
