# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/double_dds_wrapper/double_dds_wrapper.bd
# Block Designs: The module: 'double_dds_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_ad9767_0_0/double_dds_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_ad9767_0_0 || ORIG_REF_NAME==double_dds_wrapper_ad9767_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_axi_interconnect_0_0/double_dds_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==double_dds_wrapper_axi_interconnect_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_xbar_0/double_dds_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_xbar_0 || ORIG_REF_NAME==double_dds_wrapper_xbar_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds_ampl_0/double_dds_wrapper_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds_ampl_0 || ORIG_REF_NAME==double_dds_wrapper_dds_ampl_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds_offset_0/double_dds_wrapper_dds_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds_offset_0 || ORIG_REF_NAME==double_dds_wrapper_dds_offset_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_ltc2145_0_0/double_dds_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_ltc2145_0_0 || ORIG_REF_NAME==double_dds_wrapper_ltc2145_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_proc_sys_reset_0_0/double_dds_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==double_dds_wrapper_proc_sys_reset_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_processing_system7_0_0/double_dds_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_processing_system7_0_0 || ORIG_REF_NAME==double_dds_wrapper_processing_system7_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_redpitaya_adc_dac_clk_0_0/double_dds_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==double_dds_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_twoInMult_0_0/double_dds_wrapper_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_twoInMult_0_0 || ORIG_REF_NAME==double_dds_wrapper_twoInMult_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_xlconstant_0_0/double_dds_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_xlconstant_0_0 || ORIG_REF_NAME==double_dds_wrapper_xlconstant_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_xlslice_0_0/double_dds_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_xlslice_0_0 || ORIG_REF_NAME==double_dds_wrapper_xlslice_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds_ampl_1/double_dds_wrapper_dds_ampl_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds_ampl_1 || ORIG_REF_NAME==double_dds_wrapper_dds_ampl_1}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_xlconstant_0_1/double_dds_wrapper_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_xlconstant_0_1 || ORIG_REF_NAME==double_dds_wrapper_xlconstant_0_1}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds1_offset_0/double_dds_wrapper_dds1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds1_offset_0 || ORIG_REF_NAME==double_dds_wrapper_dds1_offset_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_xlslice_0_1/double_dds_wrapper_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_xlslice_0_1 || ORIG_REF_NAME==double_dds_wrapper_xlslice_0_1}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds1_twoInMult_0_0/double_dds_wrapper_dds1_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds1_twoInMult_0_0 || ORIG_REF_NAME==double_dds_wrapper_dds1_twoInMult_0_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds1_ampl_0/double_dds_wrapper_dds1_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds1_ampl_0 || ORIG_REF_NAME==double_dds_wrapper_dds1_ampl_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds1_phase_0/double_dds_wrapper_dds1_phase_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds1_phase_0 || ORIG_REF_NAME==double_dds_wrapper_dds1_phase_0}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_nco_counter_0_2/double_dds_wrapper_nco_counter_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_nco_counter_0_2 || ORIG_REF_NAME==double_dds_wrapper_nco_counter_0_2}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_dds1_nco_counter_1/double_dds_wrapper_dds1_nco_counter_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_dds1_nco_counter_1 || ORIG_REF_NAME==double_dds_wrapper_dds1_nco_counter_1}]

# IP: bd/double_dds_wrapper/ip/double_dds_wrapper_auto_pc_0/double_dds_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_wrapper_auto_pc_0 || ORIG_REF_NAME==double_dds_wrapper_auto_pc_0}]

# XDC: bd/double_dds_wrapper/double_dds_wrapper_ooc.xdc
