# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/pid_vco_wrapper/pid_vco_wrapper.bd
# Block Designs: The module: 'pid_vco_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_ad9767_0_0/pid_vco_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_ad9767_0_0 || ORIG_REF_NAME==pid_vco_wrapper_ad9767_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_adc1_offset_0/pid_vco_wrapper_adc1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_adc1_offset_0 || ORIG_REF_NAME==pid_vco_wrapper_adc1_offset_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_axi_interconnect_0_0/pid_vco_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==pid_vco_wrapper_axi_interconnect_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_xbar_0/pid_vco_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_xbar_0 || ORIG_REF_NAME==pid_vco_wrapper_xbar_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dac1_offset_0/pid_vco_wrapper_dac1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dac1_offset_0 || ORIG_REF_NAME==pid_vco_wrapper_dac1_offset_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_ampl_0/pid_vco_wrapper_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_ampl_0 || ORIG_REF_NAME==pid_vco_wrapper_dds_ampl_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_f0_0/pid_vco_wrapper_dds_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_f0_0 || ORIG_REF_NAME==pid_vco_wrapper_dds_f0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_nco_0/pid_vco_wrapper_dds_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_nco_0 || ORIG_REF_NAME==pid_vco_wrapper_dds_nco_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_offset_0/pid_vco_wrapper_dds_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_offset_0 || ORIG_REF_NAME==pid_vco_wrapper_dds_offset_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_range_0/pid_vco_wrapper_dds_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_range_0 || ORIG_REF_NAME==pid_vco_wrapper_dds_range_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dupplReal_1_to_2_0_0/pid_vco_wrapper_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==pid_vco_wrapper_dupplReal_1_to_2_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_expanderReal_0_0/pid_vco_wrapper_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_expanderReal_0_0 || ORIG_REF_NAME==pid_vco_wrapper_expanderReal_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_ltc2145_0_0/pid_vco_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_ltc2145_0_0 || ORIG_REF_NAME==pid_vco_wrapper_ltc2145_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_proc_sys_reset_0_0/pid_vco_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==pid_vco_wrapper_proc_sys_reset_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_processing_system7_0_0/pid_vco_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_processing_system7_0_0 || ORIG_REF_NAME==pid_vco_wrapper_processing_system7_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0/pid_vco_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==pid_vco_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_twoInMult_dds_ampl_0/pid_vco_wrapper_twoInMult_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_twoInMult_dds_ampl_0 || ORIG_REF_NAME==pid_vco_wrapper_twoInMult_dds_ampl_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_twoInMult_dds_range_0/pid_vco_wrapper_twoInMult_dds_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_twoInMult_dds_range_0 || ORIG_REF_NAME==pid_vco_wrapper_twoInMult_dds_range_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_xlconstant_0_0/pid_vco_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_xlconstant_0_0 || ORIG_REF_NAME==pid_vco_wrapper_xlconstant_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_xlslice_0_0/pid_vco_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_xlslice_0_0 || ORIG_REF_NAME==pid_vco_wrapper_xlslice_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_red_pitaya_pidv3_0_0/pid_vco_wrapper_red_pitaya_pidv3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_red_pitaya_pidv3_0_0 || ORIG_REF_NAME==pid_vco_wrapper_red_pitaya_pidv3_0_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_dds_range_1/pid_vco_wrapper_dds_range_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_dds_range_1 || ORIG_REF_NAME==pid_vco_wrapper_dds_range_1}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_pid_kp_0/pid_vco_wrapper_pid_kp_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_pid_kp_0 || ORIG_REF_NAME==pid_vco_wrapper_pid_kp_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_pid_ki_0/pid_vco_wrapper_pid_ki_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_pid_ki_0 || ORIG_REF_NAME==pid_vco_wrapper_pid_ki_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_pid_kd_0/pid_vco_wrapper_pid_kd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_pid_kd_0 || ORIG_REF_NAME==pid_vco_wrapper_pid_kd_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_xlconstant_1_0/pid_vco_wrapper_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_xlconstant_1_0 || ORIG_REF_NAME==pid_vco_wrapper_xlconstant_1_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_pid_rst_int_0/pid_vco_wrapper_pid_rst_int_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_pid_rst_int_0 || ORIG_REF_NAME==pid_vco_wrapper_pid_rst_int_0}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_pid_kp_1/pid_vco_wrapper_pid_kp_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_pid_kp_1 || ORIG_REF_NAME==pid_vco_wrapper_pid_kp_1}]

# IP: bd/pid_vco_wrapper/ip/pid_vco_wrapper_auto_pc_0/pid_vco_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_vco_wrapper_auto_pc_0 || ORIG_REF_NAME==pid_vco_wrapper_auto_pc_0}]

# XDC: bd/pid_vco_wrapper/pid_vco_wrapper_ooc.xdc
