---------------------------------------------------------------------------
-- Company     : Automaticaly generated by POD
-- Author(s)   : 
--
-- Creation Date : 2016-09-13
-- File          : Top_red_pseudogen_dds.vhd
--
-- Abstract :
-- insert a description here
--
---------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.numeric_std.all;

entity top_red_pseudogen_dds is

    port
    (
    -- nco-test
        nco_test_o: out std_logic;
        pseudo_test_o : out std_logic;
    -- analog-clk_in
        analog_adc_clk_p_i: in std_logic;
    -- analog-clk_in
        analog_adc_clk_n_i: in std_logic;
    -- analog-phys_adc
        analog_phys_adc_clk_cdcs: out std_logic;
    -- analog-phys_adc
        analog_phys_adc_data_a_i: in std_logic_vector(13 downto 0);
    -- analog-phys_adc
        analog_phys_adc_data_b_i: in std_logic_vector(13 downto 0);
    -- analog-phys_dac
        analog_phys_dac_wrt_o: out std_logic;
    -- analog-phys_dac
        analog_phys_dac_sel_o: out std_logic;
    -- analog-phys_dac
        analog_phys_dac_clk_o: out std_logic;
    -- analog-phys_dac
        analog_phys_dac_rst_o: out std_logic;
    -- analog-phys_dac
        analog_phys_dac_data_o: out std_logic_vector(13 downto 0);
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_ddr_vrn: inout std_logic;
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_ddr_vrp: inout std_logic;
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_mio: inout std_logic_vector(53 downto 0);
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_ps_clk: inout std_logic;
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_ps_porb: inout std_logic;
    -- redpitaya_axi_wrapper00-fixed_io
        redpitaya_axi_wrapper00_FIXED_IO_ps_srstb: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_addr: inout std_logic_vector(14 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_ba: inout std_logic_vector(2 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_cas_n: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_ck_n: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_ck_p: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_cke: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_cs_n: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_dm: inout std_logic_vector(3 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_dq: inout std_logic_vector(31 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_dqs_n: inout std_logic_vector(3 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_dqs_p: inout std_logic_vector(3 downto 0);
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_odt: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_ras_n: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_reset_n: inout std_logic;
    -- redpitaya_axi_wrapper00-ram
        redpitaya_axi_wrapper00_DDR_we_n: inout std_logic
    );
end entity top_red_pseudogen_dds;

architecture top_red_pseudogen_dds_1 of top_red_pseudogen_dds is
    ------------------------
    -- declare components --
    ------------------------


    component redpitaya_adc_dac
        port (
            -- adc_a_out
            adc_data_a_en_o: out std_logic;
            adc_data_a_clk_o: out std_logic;
            adc_data_a_o: out std_logic_vector(13 downto 0);
            -- adc_b_out
            adc_data_b_en_o: out std_logic;
            adc_data_b_clk_o: out std_logic;
            adc_data_b_o: out std_logic_vector(13 downto 0);
            -- dac_a_in
            dac_dat_a_en_i: in std_logic;
            dac_dat_a_clk_i: in std_logic;
            dac_dat_a_i: in std_logic_vector(13 downto 0);
            -- dac_b_in
            dac_dat_b_en_i: in std_logic;
            dac_dat_b_clk_i: in std_logic;
            dac_dat_b_i: in std_logic_vector(13 downto 0);
            -- adc_clk
            adc_clk_o: out std_logic;
            -- dac_clk
            dac_clk_o: out std_logic;
            -- ser_clk
            ser_clk_o: out std_logic;
            -- candrinput
            clk_i: in std_logic;
            adc_rst_i: in std_logic;
            -- clk_in
            adc_clk_p_i: in std_logic;
            adc_clk_n_i: in std_logic;
            -- phys_adc
            phys_adc_clk_cdcs: out std_logic;
            phys_adc_data_a_i: in std_logic_vector(13 downto 0);
            phys_adc_data_b_i: in std_logic_vector(13 downto 0);
            -- phys_dac
            phys_dac_wrt_o: out std_logic;
            phys_dac_sel_o: out std_logic;
            phys_dac_clk_o: out std_logic;
            phys_dac_rst_o: out std_logic;
            phys_dac_data_o: out std_logic_vector(13 downto 0)
        );
    end component;

    component convertComplexToReal
        generic(
            DATA_SIZE : natural := 14
        );
        port (
            -- data_in
            data_i_i: in std_logic_vector(13 downto 0);
            data_q_i: in std_logic_vector(13 downto 0);
            data_eof_i: in std_logic;
            data_en_i: in std_logic;
            data_clk_i: in std_logic;
            -- data1_out
            data1_o: out std_logic_vector(13 downto 0);
            data1_eof_o: out std_logic;
            data1_en_o: out std_logic;
            data1_clk_o: out std_logic;
            -- data2_out
            data2_o: out std_logic_vector(13 downto 0);
            data2_eof_o: out std_logic;
            data2_en_o: out std_logic;
            data2_clk_o: out std_logic
        );
    end component;

    component redpitaya_axi_wrapper00_axim
        port (
            -- nco_axis
            nco_s00_axi_aclk: out std_logic;
            nco_s00_axi_reset: out std_logic;
            nco_s00_axi_araddr: out std_logic_vector(1 downto 0);
            nco_s00_axi_arprot: out std_logic_vector(2 downto 0);
            nco_s00_axi_arready: in std_logic;
            nco_s00_axi_arvalid: out std_logic;
            nco_s00_axi_awaddr: out std_logic_vector(1 downto 0);
            nco_s00_axi_awprot: out std_logic_vector(2 downto 0);
            nco_s00_axi_awready: in std_logic;
            nco_s00_axi_awvalid: out std_logic;
            nco_s00_axi_bready: out std_logic;
            nco_s00_axi_bresp: in std_logic_vector(1 downto 0);
            nco_s00_axi_bvalid: in std_logic;
            nco_s00_axi_rdata: in std_logic_vector(31 downto 0);
            nco_s00_axi_rready: out std_logic;
            nco_s00_axi_rresp: in std_logic_vector(1 downto 0);
            nco_s00_axi_rvalid: in std_logic;
            nco_s00_axi_wdata: out std_logic_vector(31 downto 0);
            nco_s00_axi_wready: in std_logic;
            nco_s00_axi_wstrb: out std_logic_vector(3 downto 0);
            nco_s00_axi_wvalid: out std_logic;
            -- gene_axis
            gene_s00_axi_aclk: out std_logic;
            gene_s00_axi_reset: out std_logic;
            gene_s00_axi_araddr: out std_logic_vector(1 downto 0);
            gene_s00_axi_arprot: out std_logic_vector(2 downto 0);
            gene_s00_axi_arready: in std_logic;
            gene_s00_axi_arvalid: out std_logic;
            gene_s00_axi_awaddr: out std_logic_vector(1 downto 0);
            gene_s00_axi_awprot: out std_logic_vector(2 downto 0);
            gene_s00_axi_awready: in std_logic;
            gene_s00_axi_awvalid: out std_logic;
            gene_s00_axi_bready: out std_logic;
            gene_s00_axi_bresp: in std_logic_vector(1 downto 0);
            gene_s00_axi_bvalid: in std_logic;
            gene_s00_axi_rdata: in std_logic_vector(31 downto 0);
            gene_s00_axi_rready: out std_logic;
            gene_s00_axi_rresp: in std_logic_vector(1 downto 0);
            gene_s00_axi_rvalid: in std_logic;
            gene_s00_axi_wdata: out std_logic_vector(31 downto 0);
            gene_s00_axi_wready: in std_logic;
            gene_s00_axi_wstrb: out std_logic_vector(3 downto 0);
            gene_s00_axi_wvalid: out std_logic;
            -- redpitaya_axi_wrapper00_axim
            redpitaya_axi_wrapper00_M00_AXI_clk_o: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_rst_o: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_araddr: in std_logic_vector(31 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_arprot: in std_logic_vector(2 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_arready: out std_logic;
            redpitaya_axi_wrapper00_M00_AXI_arvalid: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_awaddr: in std_logic_vector(31 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_awprot: in std_logic_vector(2 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_awready: out std_logic;
            redpitaya_axi_wrapper00_M00_AXI_awvalid: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_bready: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_bresp: out std_logic_vector(1 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_bvalid: out std_logic;
            redpitaya_axi_wrapper00_M00_AXI_rdata: out std_logic_vector(31 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_rready: in std_logic;
            redpitaya_axi_wrapper00_M00_AXI_rresp: out std_logic_vector(1 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_rvalid: out std_logic;
            redpitaya_axi_wrapper00_M00_AXI_wdata: in std_logic_vector(31 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_wready: out std_logic;
            redpitaya_axi_wrapper00_M00_AXI_wstrb: in std_logic_vector(3 downto 0);
            redpitaya_axi_wrapper00_M00_AXI_wvalid: in std_logic
        );
    end component;

    component pseudo_generateur_real
        generic(
            id : natural := 2;
            PRESCALER : natural := 10;
            DATA_SIZE : natural := 12;
            C_S00_AXI_DATA_WIDTH : integer := 32;
            C_S00_AXI_ADDR_WIDTH : integer := 2
        );
        port (
            -- axis
            s00_axi_aclk: in std_logic;
            s00_axi_reset: in std_logic;
            s00_axi_araddr: in std_logic_vector(1 downto 0);
            s00_axi_arprot: in std_logic_vector(2 downto 0);
            s00_axi_arready: out std_logic;
            s00_axi_arvalid: in std_logic;
            s00_axi_awaddr: in std_logic_vector(1 downto 0);
            s00_axi_awprot: in std_logic_vector(2 downto 0);
            s00_axi_awready: out std_logic;
            s00_axi_awvalid: in std_logic;
            s00_axi_bready: in std_logic;
            s00_axi_bresp: out std_logic_vector(1 downto 0);
            s00_axi_bvalid: out std_logic;
            s00_axi_rdata: out std_logic_vector(31 downto 0);
            s00_axi_rready: in std_logic;
            s00_axi_rresp: out std_logic_vector(1 downto 0);
            s00_axi_rvalid: out std_logic;
            s00_axi_wdata: in std_logic_vector(31 downto 0);
            s00_axi_wready: out std_logic;
            s00_axi_wstrb: in std_logic_vector(3 downto 0);
            s00_axi_wvalid: in std_logic;
            -- processing_clk
            processing_clk_i: in std_logic;
            test_o : out std_logic;
            -- data_out
            data_o: out std_logic_vector(11 downto 0);
            data_en_o: out std_logic;
            data_clk_o: out std_logic
        );
    end component;

    component nco_counter
        generic(
            id : natural := 1;
            DATA_SIZE : natural := 14;
            COUNTER_SIZE : natural := 32;
            LUT_SIZE : natural := 12;
            C_S00_AXI_DATA_WIDTH : integer := 32;
            C_S00_AXI_ADDR_WIDTH : integer := 2
        );
        port (
            -- axis
            s00_axi_aclk: in std_logic;
            s00_axi_reset: in std_logic;
            s00_axi_araddr: in std_logic_vector(1 downto 0);
            s00_axi_arprot: in std_logic_vector(2 downto 0);
            s00_axi_arready: out std_logic;
            s00_axi_arvalid: in std_logic;
            s00_axi_awaddr: in std_logic_vector(1 downto 0);
            s00_axi_awprot: in std_logic_vector(2 downto 0);
            s00_axi_awready: out std_logic;
            s00_axi_awvalid: in std_logic;
            s00_axi_bready: in std_logic;
            s00_axi_bresp: out std_logic_vector(1 downto 0);
            s00_axi_bvalid: out std_logic;
            s00_axi_rdata: out std_logic_vector(31 downto 0);
            s00_axi_rready: in std_logic;
            s00_axi_rresp: out std_logic_vector(1 downto 0);
            s00_axi_rvalid: out std_logic;
            s00_axi_wdata: in std_logic_vector(31 downto 0);
            s00_axi_wready: out std_logic;
            s00_axi_wstrb: in std_logic_vector(3 downto 0);
            s00_axi_wvalid: in std_logic;
            -- processing_clk
            processing_clk_i: in std_logic;
            -- pinc_in
            pinc_i: in std_logic_vector(31 downto 0);
            pinc_en_i: in std_logic;
            pinc_clk_i: in std_logic;
            -- poff_in
            poff_i: in std_logic_vector(11 downto 0);
            poff_en_i: in std_logic;
            poff_clk_i: in std_logic;
            -- dds_out
            dds_cos_o: out std_logic_vector(13 downto 0);
            dds_sin_o: out std_logic_vector(13 downto 0);
            dds_en_o: out std_logic;
            dds_clk_o: out std_logic;
            -- square_out
            cos_fake_o: out std_logic;
            sin_fake_o: out std_logic;
            wave_en_o: out std_logic;
            wave_clk_o: out std_logic;
            -- test
            test_o: out std_logic
        );
    end component;

    component redpitaya_axi_wrapper00_candroutput
        port (
            -- analog_candrinput
            analog_clk_i: out std_logic;
            analog_adc_rst_i: out std_logic;
            -- redpitaya_axi_wrapper00_candroutput
            redpitaya_axi_wrapper00_rst_o: in std_logic;
            redpitaya_axi_wrapper00_clk_o: in std_logic
        );
    end component;

    component redpitaya_axi_wrapper
        port (
            -- candroutput
            rst_o: out std_logic;
            clk_o: out std_logic;
            -- FCLK_CLK1
            FCLK_CLK1: out std_logic;
            -- axim
            M00_AXI_clk_o: out std_logic;
            M00_AXI_rst_o: out std_logic;
            M00_AXI_araddr: out std_logic_vector(31 downto 0);
            M00_AXI_arprot: out std_logic_vector(2 downto 0);
            M00_AXI_arready: in std_logic;
            M00_AXI_arvalid: out std_logic;
            M00_AXI_awaddr: out std_logic_vector(31 downto 0);
            M00_AXI_awprot: out std_logic_vector(2 downto 0);
            M00_AXI_awready: in std_logic;
            M00_AXI_awvalid: out std_logic;
            M00_AXI_bready: out std_logic;
            M00_AXI_bresp: in std_logic_vector(1 downto 0);
            M00_AXI_bvalid: in std_logic;
            M00_AXI_rdata: in std_logic_vector(31 downto 0);
            M00_AXI_rready: out std_logic;
            M00_AXI_rresp: in std_logic_vector(1 downto 0);
            M00_AXI_rvalid: in std_logic;
            M00_AXI_wdata: out std_logic_vector(31 downto 0);
            M00_AXI_wready: in std_logic;
            M00_AXI_wstrb: out std_logic_vector(3 downto 0);
            M00_AXI_wvalid: out std_logic;
            -- ram
            DDR_addr: inout std_logic_vector(14 downto 0);
            DDR_ba: inout std_logic_vector(2 downto 0);
            DDR_cas_n: inout std_logic;
            DDR_ck_n: inout std_logic;
            DDR_ck_p: inout std_logic;
            DDR_cke: inout std_logic;
            DDR_cs_n: inout std_logic;
            DDR_dm: inout std_logic_vector(3 downto 0);
            DDR_dq: inout std_logic_vector(31 downto 0);
            DDR_dqs_n: inout std_logic_vector(3 downto 0);
            DDR_dqs_p: inout std_logic_vector(3 downto 0);
            DDR_odt: inout std_logic;
            DDR_ras_n: inout std_logic;
            DDR_reset_n: inout std_logic;
            DDR_we_n: inout std_logic;
            -- fixed_io
            FIXED_IO_ddr_vrn: inout std_logic;
            FIXED_IO_ddr_vrp: inout std_logic;
            FIXED_IO_mio: inout std_logic_vector(53 downto 0);
            FIXED_IO_ps_clk: inout std_logic;
            FIXED_IO_ps_porb: inout std_logic;
            FIXED_IO_ps_srstb: inout std_logic
        );
    end component;
    -------------------------
    -- Signals declaration --
    -------------------------


    -- redpitaya_axi_wrapper00
    -- candroutput
    signal redpitaya_axi_wrapper00_rst_o: std_logic;
    signal redpitaya_axi_wrapper00_clk_o: std_logic;
    -- FCLK_CLK1
    -- axim
    signal redpitaya_axi_wrapper00_M00_AXI_clk_o: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_rst_o: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_araddr: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_arprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_arready: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_arvalid: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_awaddr: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_awprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_awready: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_awvalid: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_bready: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_bresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_bvalid: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_rdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_rready: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_rresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_rvalid: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_wdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_wready: std_logic;
    signal redpitaya_axi_wrapper00_M00_AXI_wstrb: std_logic_vector(3 downto 0);
    signal redpitaya_axi_wrapper00_M00_AXI_wvalid: std_logic;
    -- ram
    -- fixed_io

    -- analog
    -- adc_a_out
    -- adc_b_out
    -- dac_a_in
    signal analog_dac_dat_a_en_i: std_logic;
    signal analog_dac_dat_a_clk_i: std_logic;
    signal analog_dac_dat_a_i: std_logic_vector(13 downto 0);
    -- dac_b_in
    signal analog_dac_dat_b_en_i: std_logic;
    signal analog_dac_dat_b_clk_i: std_logic;
    signal analog_dac_dat_b_i: std_logic_vector(13 downto 0);
    -- adc_clk
    -- dac_clk
    signal analog_dac_clk_o: std_logic;
    -- ser_clk
    -- candrinput
    signal analog_clk_i: std_logic;
    signal analog_adc_rst_i: std_logic;
    -- clk_in
    -- phys_adc
    -- phys_dac

    -- nco
    -- axis
    signal nco_s00_axi_aclk: std_logic;
    signal nco_s00_axi_reset: std_logic;
    signal nco_s00_axi_araddr: std_logic_vector(1 downto 0);
    signal nco_s00_axi_arprot: std_logic_vector(2 downto 0);
    signal nco_s00_axi_arready: std_logic;
    signal nco_s00_axi_arvalid: std_logic;
    signal nco_s00_axi_awaddr: std_logic_vector(1 downto 0);
    signal nco_s00_axi_awprot: std_logic_vector(2 downto 0);
    signal nco_s00_axi_awready: std_logic;
    signal nco_s00_axi_awvalid: std_logic;
    signal nco_s00_axi_bready: std_logic;
    signal nco_s00_axi_bresp: std_logic_vector(1 downto 0);
    signal nco_s00_axi_bvalid: std_logic;
    signal nco_s00_axi_rdata: std_logic_vector(31 downto 0);
    signal nco_s00_axi_rready: std_logic;
    signal nco_s00_axi_rresp: std_logic_vector(1 downto 0);
    signal nco_s00_axi_rvalid: std_logic;
    signal nco_s00_axi_wdata: std_logic_vector(31 downto 0);
    signal nco_s00_axi_wready: std_logic;
    signal nco_s00_axi_wstrb: std_logic_vector(3 downto 0);
    signal nco_s00_axi_wvalid: std_logic;
    -- processing_clk
    signal nco_processing_clk_i: std_logic;
    -- pinc_in
    -- poff_in
    signal nco_poff_i: std_logic_vector(11 downto 0);
    signal nco_poff_en_i: std_logic;
    signal nco_poff_clk_i: std_logic;
    -- dds_out
    signal nco_dds_cos_o: std_logic_vector(13 downto 0);
    signal nco_dds_sin_o: std_logic_vector(13 downto 0);
    signal nco_dds_en_o: std_logic;
    signal nco_dds_clk_o: std_logic;
    -- square_out
    -- test

    -- gene
    -- axis
    signal gene_s00_axi_aclk: std_logic;
    signal gene_s00_axi_reset: std_logic;
    signal gene_s00_axi_araddr: std_logic_vector(1 downto 0);
    signal gene_s00_axi_arprot: std_logic_vector(2 downto 0);
    signal gene_s00_axi_arready: std_logic;
    signal gene_s00_axi_arvalid: std_logic;
    signal gene_s00_axi_awaddr: std_logic_vector(1 downto 0);
    signal gene_s00_axi_awprot: std_logic_vector(2 downto 0);
    signal gene_s00_axi_awready: std_logic;
    signal gene_s00_axi_awvalid: std_logic;
    signal gene_s00_axi_bready: std_logic;
    signal gene_s00_axi_bresp: std_logic_vector(1 downto 0);
    signal gene_s00_axi_bvalid: std_logic;
    signal gene_s00_axi_rdata: std_logic_vector(31 downto 0);
    signal gene_s00_axi_rready: std_logic;
    signal gene_s00_axi_rresp: std_logic_vector(1 downto 0);
    signal gene_s00_axi_rvalid: std_logic;
    signal gene_s00_axi_wdata: std_logic_vector(31 downto 0);
    signal gene_s00_axi_wready: std_logic;
    signal gene_s00_axi_wstrb: std_logic_vector(3 downto 0);
    signal gene_s00_axi_wvalid: std_logic;
    -- processing_clk
    signal gene_processing_clk_i: std_logic;
    -- data_out
    signal gene_data_o: std_logic_vector(11 downto 0);
    signal gene_data_en_o: std_logic;
    signal gene_data_clk_o: std_logic;

    -- convert
    -- data_in
    signal convert_data_i_i: std_logic_vector(13 downto 0);
    signal convert_data_q_i: std_logic_vector(13 downto 0);
    signal convert_data_en_i: std_logic;
    signal convert_data_clk_i: std_logic;
    -- data1_out
    signal convert_data1_o: std_logic_vector(13 downto 0);
    signal convert_data1_en_o: std_logic;
    signal convert_data1_clk_o: std_logic;
    -- data2_out
    signal convert_data2_o: std_logic_vector(13 downto 0);
    signal convert_data2_en_o: std_logic;
    signal convert_data2_clk_o: std_logic;

    -- redpitaya_axi_wrapper00_axim_intercon
    -- nco_axis
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_aclk: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_reset: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_araddr: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awaddr: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wstrb: std_logic_vector(3 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wvalid: std_logic;
    -- gene_axis
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_aclk: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_reset: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_araddr: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awaddr: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wstrb: std_logic_vector(3 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wvalid: std_logic;
    -- redpitaya_axi_wrapper00_axim
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_clk_o: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rst_o: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_araddr: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awaddr: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awprot: std_logic_vector(2 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rresp: std_logic_vector(1 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rvalid: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wdata: std_logic_vector(31 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wready: std_logic;
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wstrb: std_logic_vector(3 downto 0);
    signal redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wvalid: std_logic;

    -- redpitaya_axi_wrapper00_candroutput_intercon
    -- analog_candrinput
    signal redpitaya_axi_wrapper00_candroutput_intercon_analog_clk_i: std_logic;
    signal redpitaya_axi_wrapper00_candroutput_intercon_analog_adc_rst_i: std_logic;
    -- redpitaya_axi_wrapper00_candroutput
    signal redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_rst_o: std_logic;
    signal redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_clk_o: std_logic;

    -- void pins

begin

    ----------------
    -- Set forces --
    ----------------

    -----------------------
    -- declare instances --
    -----------------------


    redpitaya_axi_wrapper00 : redpitaya_axi_wrapper
    port map (
            -- candroutput
            rst_o => redpitaya_axi_wrapper00_rst_o,
            clk_o => redpitaya_axi_wrapper00_clk_o,
            -- FCLK_CLK1
            FCLK_CLK1 => open,
            -- axim
            M00_AXI_clk_o => redpitaya_axi_wrapper00_M00_AXI_clk_o,
            M00_AXI_rst_o => redpitaya_axi_wrapper00_M00_AXI_rst_o,
            M00_AXI_araddr => redpitaya_axi_wrapper00_M00_AXI_araddr,
            M00_AXI_arprot => redpitaya_axi_wrapper00_M00_AXI_arprot,
            M00_AXI_arready => redpitaya_axi_wrapper00_M00_AXI_arready,
            M00_AXI_arvalid => redpitaya_axi_wrapper00_M00_AXI_arvalid,
            M00_AXI_awaddr => redpitaya_axi_wrapper00_M00_AXI_awaddr,
            M00_AXI_awprot => redpitaya_axi_wrapper00_M00_AXI_awprot,
            M00_AXI_awready => redpitaya_axi_wrapper00_M00_AXI_awready,
            M00_AXI_awvalid => redpitaya_axi_wrapper00_M00_AXI_awvalid,
            M00_AXI_bready => redpitaya_axi_wrapper00_M00_AXI_bready,
            M00_AXI_bresp => redpitaya_axi_wrapper00_M00_AXI_bresp,
            M00_AXI_bvalid => redpitaya_axi_wrapper00_M00_AXI_bvalid,
            M00_AXI_rdata => redpitaya_axi_wrapper00_M00_AXI_rdata,
            M00_AXI_rready => redpitaya_axi_wrapper00_M00_AXI_rready,
            M00_AXI_rresp => redpitaya_axi_wrapper00_M00_AXI_rresp,
            M00_AXI_rvalid => redpitaya_axi_wrapper00_M00_AXI_rvalid,
            M00_AXI_wdata => redpitaya_axi_wrapper00_M00_AXI_wdata,
            M00_AXI_wready => redpitaya_axi_wrapper00_M00_AXI_wready,
            M00_AXI_wstrb => redpitaya_axi_wrapper00_M00_AXI_wstrb,
            M00_AXI_wvalid => redpitaya_axi_wrapper00_M00_AXI_wvalid,
            -- ram
            DDR_addr => redpitaya_axi_wrapper00_DDR_addr,
            DDR_ba => redpitaya_axi_wrapper00_DDR_ba,
            DDR_cas_n => redpitaya_axi_wrapper00_DDR_cas_n,
            DDR_ck_n => redpitaya_axi_wrapper00_DDR_ck_n,
            DDR_ck_p => redpitaya_axi_wrapper00_DDR_ck_p,
            DDR_cke => redpitaya_axi_wrapper00_DDR_cke,
            DDR_cs_n => redpitaya_axi_wrapper00_DDR_cs_n,
            DDR_dm => redpitaya_axi_wrapper00_DDR_dm,
            DDR_dq => redpitaya_axi_wrapper00_DDR_dq,
            DDR_dqs_n => redpitaya_axi_wrapper00_DDR_dqs_n,
            DDR_dqs_p => redpitaya_axi_wrapper00_DDR_dqs_p,
            DDR_odt => redpitaya_axi_wrapper00_DDR_odt,
            DDR_ras_n => redpitaya_axi_wrapper00_DDR_ras_n,
            DDR_reset_n => redpitaya_axi_wrapper00_DDR_reset_n,
            DDR_we_n => redpitaya_axi_wrapper00_DDR_we_n,
            -- fixed_io
            FIXED_IO_ddr_vrn => redpitaya_axi_wrapper00_FIXED_IO_ddr_vrn,
            FIXED_IO_ddr_vrp => redpitaya_axi_wrapper00_FIXED_IO_ddr_vrp,
            FIXED_IO_mio => redpitaya_axi_wrapper00_FIXED_IO_mio,
            FIXED_IO_ps_clk => redpitaya_axi_wrapper00_FIXED_IO_ps_clk,
            FIXED_IO_ps_porb => redpitaya_axi_wrapper00_FIXED_IO_ps_porb,
            FIXED_IO_ps_srstb => redpitaya_axi_wrapper00_FIXED_IO_ps_srstb
            );

    analog : redpitaya_adc_dac
    port map (
            -- adc_a_out
            adc_data_a_en_o => open,
            adc_data_a_clk_o => open,
            adc_data_a_o => open,
            -- adc_b_out
            adc_data_b_en_o => open,
            adc_data_b_clk_o => open,
            adc_data_b_o => open,
            -- dac_a_in
            dac_dat_a_en_i => analog_dac_dat_a_en_i,
            dac_dat_a_clk_i => analog_dac_dat_a_clk_i,
            dac_dat_a_i => analog_dac_dat_a_i,
            -- dac_b_in
            dac_dat_b_en_i => analog_dac_dat_b_en_i,
            dac_dat_b_clk_i => analog_dac_dat_b_clk_i,
            dac_dat_b_i => analog_dac_dat_b_i,
            -- adc_clk
            adc_clk_o => open,
            -- dac_clk
            dac_clk_o => analog_dac_clk_o,
            -- ser_clk
            ser_clk_o => open,
            -- candrinput
            clk_i => analog_clk_i,
            adc_rst_i => analog_adc_rst_i,
            -- clk_in
            adc_clk_p_i => analog_adc_clk_p_i,
            adc_clk_n_i => analog_adc_clk_n_i,
            -- phys_adc
            phys_adc_clk_cdcs => analog_phys_adc_clk_cdcs,
            phys_adc_data_a_i => analog_phys_adc_data_a_i,
            phys_adc_data_b_i => analog_phys_adc_data_b_i,
            -- phys_dac
            phys_dac_wrt_o => analog_phys_dac_wrt_o,
            phys_dac_sel_o => analog_phys_dac_sel_o,
            phys_dac_clk_o => analog_phys_dac_clk_o,
            phys_dac_rst_o => analog_phys_dac_rst_o,
            phys_dac_data_o => analog_phys_dac_data_o
            );

    nco : nco_counter
    generic map (
            id => 1,
            DATA_SIZE => 14,
            COUNTER_SIZE => 32,
            LUT_SIZE => 12,
            C_S00_AXI_DATA_WIDTH => 32,
            C_S00_AXI_ADDR_WIDTH => 2
        )
    port map (
            -- axis
            s00_axi_aclk => nco_s00_axi_aclk,
            s00_axi_reset => nco_s00_axi_reset,
            s00_axi_araddr => nco_s00_axi_araddr,
            s00_axi_arprot => nco_s00_axi_arprot,
            s00_axi_arready => nco_s00_axi_arready,
            s00_axi_arvalid => nco_s00_axi_arvalid,
            s00_axi_awaddr => nco_s00_axi_awaddr,
            s00_axi_awprot => nco_s00_axi_awprot,
            s00_axi_awready => nco_s00_axi_awready,
            s00_axi_awvalid => nco_s00_axi_awvalid,
            s00_axi_bready => nco_s00_axi_bready,
            s00_axi_bresp => nco_s00_axi_bresp,
            s00_axi_bvalid => nco_s00_axi_bvalid,
            s00_axi_rdata => nco_s00_axi_rdata,
            s00_axi_rready => nco_s00_axi_rready,
            s00_axi_rresp => nco_s00_axi_rresp,
            s00_axi_rvalid => nco_s00_axi_rvalid,
            s00_axi_wdata => nco_s00_axi_wdata,
            s00_axi_wready => nco_s00_axi_wready,
            s00_axi_wstrb => nco_s00_axi_wstrb,
            s00_axi_wvalid => nco_s00_axi_wvalid,
            -- processing_clk
            processing_clk_i => gene_processing_clk_i,
            -- pinc_in
            pinc_i => (31 downto 0 => '0'),
            pinc_en_i => '0',
            pinc_clk_i => '0',
            -- poff_in
            poff_i => nco_poff_i,
            poff_en_i => nco_poff_en_i,
            poff_clk_i => nco_poff_clk_i,
            -- dds_out
            dds_cos_o => nco_dds_cos_o,
            dds_sin_o => nco_dds_sin_o,
            dds_en_o => nco_dds_en_o,
            dds_clk_o => nco_dds_clk_o,
            -- square_out
            cos_fake_o => open,
            sin_fake_o => open,
            wave_en_o => open,
            wave_clk_o => open,
            -- test
            test_o => nco_test_o
            );
    
    gene : pseudo_generateur_real
    generic map (
            id => 2,
            PRESCALER => 10,
            DATA_SIZE => 12,
            C_S00_AXI_DATA_WIDTH => 32,
            C_S00_AXI_ADDR_WIDTH => 2
        )
    port map (
            -- axis
            s00_axi_aclk => gene_s00_axi_aclk,
            s00_axi_reset => gene_s00_axi_reset,
            s00_axi_araddr => gene_s00_axi_araddr,
            s00_axi_arprot => gene_s00_axi_arprot,
            s00_axi_arready => gene_s00_axi_arready,
            s00_axi_arvalid => gene_s00_axi_arvalid,
            s00_axi_awaddr => gene_s00_axi_awaddr,
            s00_axi_awprot => gene_s00_axi_awprot,
            s00_axi_awready => gene_s00_axi_awready,
            s00_axi_awvalid => gene_s00_axi_awvalid,
            s00_axi_bready => gene_s00_axi_bready,
            s00_axi_bresp => gene_s00_axi_bresp,
            s00_axi_bvalid => gene_s00_axi_bvalid,
            s00_axi_rdata => gene_s00_axi_rdata,
            s00_axi_rready => gene_s00_axi_rready,
            s00_axi_rresp => gene_s00_axi_rresp,
            s00_axi_rvalid => gene_s00_axi_rvalid,
            s00_axi_wdata => gene_s00_axi_wdata,
            s00_axi_wready => gene_s00_axi_wready,
            s00_axi_wstrb => gene_s00_axi_wstrb,
            s00_axi_wvalid => gene_s00_axi_wvalid,
            -- processing_clk
            processing_clk_i => gene_processing_clk_i,
            test_o => pseudo_test_o,
            -- data_out
            data_o => gene_data_o,
            data_en_o => gene_data_en_o,
            data_clk_o => gene_data_clk_o
            );

    convert : convertComplexToReal
    generic map (
            DATA_SIZE => 14
        )
    port map (
            -- data_in
            data_i_i => convert_data_i_i,
            data_q_i => convert_data_q_i,
            data_eof_i => '0',
            data_en_i => convert_data_en_i,
            data_clk_i => convert_data_clk_i,
            -- data1_out
            data1_o => convert_data1_o,
            data1_eof_o => open,
            data1_en_o => convert_data1_en_o,
            data1_clk_o => convert_data1_clk_o,
            -- data2_out
            data2_o => convert_data2_o,
            data2_eof_o => open,
            data2_en_o => convert_data2_en_o,
            data2_clk_o => convert_data2_clk_o
            );

    redpitaya_axi_wrapper00_axim_intercon : redpitaya_axi_wrapper00_axim
    port map (
            -- nco_axis
            nco_s00_axi_aclk => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_aclk,
            nco_s00_axi_reset => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_reset,
            nco_s00_axi_araddr => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_araddr,
            nco_s00_axi_arprot => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arprot,
            nco_s00_axi_arready => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arready,
            nco_s00_axi_arvalid => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arvalid,
            nco_s00_axi_awaddr => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awaddr,
            nco_s00_axi_awprot => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awprot,
            nco_s00_axi_awready => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awready,
            nco_s00_axi_awvalid => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awvalid,
            nco_s00_axi_bready => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bready,
            nco_s00_axi_bresp => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bresp,
            nco_s00_axi_bvalid => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bvalid,
            nco_s00_axi_rdata => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rdata,
            nco_s00_axi_rready => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rready,
            nco_s00_axi_rresp => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rresp,
            nco_s00_axi_rvalid => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rvalid,
            nco_s00_axi_wdata => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wdata,
            nco_s00_axi_wready => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wready,
            nco_s00_axi_wstrb => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wstrb,
            nco_s00_axi_wvalid => redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wvalid,
            -- gene_axis
            gene_s00_axi_aclk => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_aclk,
            gene_s00_axi_reset => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_reset,
            gene_s00_axi_araddr => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_araddr,
            gene_s00_axi_arprot => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arprot,
            gene_s00_axi_arready => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arready,
            gene_s00_axi_arvalid => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arvalid,
            gene_s00_axi_awaddr => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awaddr,
            gene_s00_axi_awprot => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awprot,
            gene_s00_axi_awready => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awready,
            gene_s00_axi_awvalid => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awvalid,
            gene_s00_axi_bready => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bready,
            gene_s00_axi_bresp => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bresp,
            gene_s00_axi_bvalid => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bvalid,
            gene_s00_axi_rdata => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rdata,
            gene_s00_axi_rready => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rready,
            gene_s00_axi_rresp => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rresp,
            gene_s00_axi_rvalid => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rvalid,
            gene_s00_axi_wdata => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wdata,
            gene_s00_axi_wready => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wready,
            gene_s00_axi_wstrb => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wstrb,
            gene_s00_axi_wvalid => redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wvalid,
            -- redpitaya_axi_wrapper00_axim
            redpitaya_axi_wrapper00_M00_AXI_clk_o => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_clk_o,
            redpitaya_axi_wrapper00_M00_AXI_rst_o => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rst_o,
            redpitaya_axi_wrapper00_M00_AXI_araddr => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_araddr,
            redpitaya_axi_wrapper00_M00_AXI_arprot => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arprot,
            redpitaya_axi_wrapper00_M00_AXI_arready => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arready,
            redpitaya_axi_wrapper00_M00_AXI_arvalid => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arvalid,
            redpitaya_axi_wrapper00_M00_AXI_awaddr => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awaddr,
            redpitaya_axi_wrapper00_M00_AXI_awprot => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awprot,
            redpitaya_axi_wrapper00_M00_AXI_awready => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awready,
            redpitaya_axi_wrapper00_M00_AXI_awvalid => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awvalid,
            redpitaya_axi_wrapper00_M00_AXI_bready => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bready,
            redpitaya_axi_wrapper00_M00_AXI_bresp => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bresp,
            redpitaya_axi_wrapper00_M00_AXI_bvalid => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bvalid,
            redpitaya_axi_wrapper00_M00_AXI_rdata => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rdata,
            redpitaya_axi_wrapper00_M00_AXI_rready => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rready,
            redpitaya_axi_wrapper00_M00_AXI_rresp => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rresp,
            redpitaya_axi_wrapper00_M00_AXI_rvalid => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rvalid,
            redpitaya_axi_wrapper00_M00_AXI_wdata => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wdata,
            redpitaya_axi_wrapper00_M00_AXI_wready => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wready,
            redpitaya_axi_wrapper00_M00_AXI_wstrb => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wstrb,
            redpitaya_axi_wrapper00_M00_AXI_wvalid => redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wvalid
            );

    redpitaya_axi_wrapper00_candroutput_intercon : redpitaya_axi_wrapper00_candroutput
    port map (
            -- analog_candrinput
            analog_clk_i => redpitaya_axi_wrapper00_candroutput_intercon_analog_clk_i,
            analog_adc_rst_i => redpitaya_axi_wrapper00_candroutput_intercon_analog_adc_rst_i,
            -- redpitaya_axi_wrapper00_candroutput
            redpitaya_axi_wrapper00_rst_o => redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_rst_o,
            redpitaya_axi_wrapper00_clk_o => redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_clk_o
            );

    ---------------------------
    -- instances connections --
    ---------------------------


    -- connect redpitaya_axi_wrapper00
        -- candroutput
        -- FCLK_CLK1
        -- axim
        redpitaya_axi_wrapper00_M00_AXI_arready <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arready;
        redpitaya_axi_wrapper00_M00_AXI_awready <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awready;
        redpitaya_axi_wrapper00_M00_AXI_bresp <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bresp;
        redpitaya_axi_wrapper00_M00_AXI_bvalid <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bvalid;
        redpitaya_axi_wrapper00_M00_AXI_rdata <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rdata;
        redpitaya_axi_wrapper00_M00_AXI_rresp <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rresp;
        redpitaya_axi_wrapper00_M00_AXI_rvalid <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rvalid;
        redpitaya_axi_wrapper00_M00_AXI_wready <= redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wready;
        -- ram
        -- fixed_io

    -- connect analog
        -- adc_a_out
        -- adc_b_out
        -- dac_a_in
        analog_dac_dat_a_en_i <= convert_data1_en_o;
        analog_dac_dat_a_clk_i <= convert_data1_clk_o;
        analog_dac_dat_a_i <= convert_data1_o;
        -- dac_b_in
        analog_dac_dat_b_en_i <= convert_data2_en_o;
        analog_dac_dat_b_clk_i <= convert_data2_clk_o;
        analog_dac_dat_b_i <= convert_data2_o;
        -- adc_clk
        -- dac_clk
        -- ser_clk
        -- candrinput
        analog_clk_i <= redpitaya_axi_wrapper00_candroutput_intercon_analog_clk_i;
        analog_adc_rst_i <= redpitaya_axi_wrapper00_candroutput_intercon_analog_adc_rst_i;
        -- clk_in
        -- phys_adc
        -- phys_dac

    -- connect nco
        -- axis
        nco_s00_axi_aclk <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_aclk;
        nco_s00_axi_reset <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_reset;
        nco_s00_axi_araddr <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_araddr;
        nco_s00_axi_arprot <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arprot;
        nco_s00_axi_arvalid <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arvalid;
        nco_s00_axi_awaddr <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awaddr;
        nco_s00_axi_awprot <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awprot;
        nco_s00_axi_awvalid <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awvalid;
        nco_s00_axi_bready <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bready;
        nco_s00_axi_rready <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rready;
        nco_s00_axi_wdata <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wdata;
        nco_s00_axi_wstrb <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wstrb;
        nco_s00_axi_wvalid <= redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wvalid;
        -- processing_clk
        nco_processing_clk_i <= analog_dac_clk_o;
        -- pinc_in
        -- poff_in
        nco_poff_i <= gene_data_o;
        nco_poff_en_i <= gene_data_en_o;
        nco_poff_clk_i <= gene_data_clk_o;
        -- dds_out
        -- square_out
        -- test

    -- connect gene
        -- axis
        gene_s00_axi_aclk <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_aclk;
        gene_s00_axi_reset <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_reset;
        gene_s00_axi_araddr <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_araddr;
        gene_s00_axi_arprot <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arprot;
        gene_s00_axi_arvalid <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arvalid;
        gene_s00_axi_awaddr <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awaddr;
        gene_s00_axi_awprot <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awprot;
        gene_s00_axi_awvalid <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awvalid;
        gene_s00_axi_bready <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bready;
        gene_s00_axi_rready <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rready;
        gene_s00_axi_wdata <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wdata;
        gene_s00_axi_wstrb <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wstrb;
        gene_s00_axi_wvalid <= redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wvalid;
        -- processing_clk
        gene_processing_clk_i <= analog_dac_clk_o;
        -- data_out

    -- connect convert
        -- data_in
        convert_data_i_i <= nco_dds_cos_o;
        convert_data_q_i <= nco_dds_sin_o;
        convert_data_en_i <= nco_dds_en_o;
        convert_data_clk_i <= nco_dds_clk_o;
        -- data1_out
        -- data2_out

    -- connect redpitaya_axi_wrapper00_axim_intercon
        -- nco_axis
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_arready <= nco_s00_axi_arready;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_awready <= nco_s00_axi_awready;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bresp <= nco_s00_axi_bresp;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_bvalid <= nco_s00_axi_bvalid;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rdata <= nco_s00_axi_rdata;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rresp <= nco_s00_axi_rresp;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_rvalid <= nco_s00_axi_rvalid;
        redpitaya_axi_wrapper00_axim_intercon_nco_s00_axi_wready <= nco_s00_axi_wready;
        -- gene_axis
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_arready <= gene_s00_axi_arready;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_awready <= gene_s00_axi_awready;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bresp <= gene_s00_axi_bresp;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_bvalid <= gene_s00_axi_bvalid;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rdata <= gene_s00_axi_rdata;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rresp <= gene_s00_axi_rresp;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_rvalid <= gene_s00_axi_rvalid;
        redpitaya_axi_wrapper00_axim_intercon_gene_s00_axi_wready <= gene_s00_axi_wready;
        -- redpitaya_axi_wrapper00_axim
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_clk_o <= redpitaya_axi_wrapper00_M00_AXI_clk_o;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rst_o <= redpitaya_axi_wrapper00_M00_AXI_rst_o;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_araddr <= redpitaya_axi_wrapper00_M00_AXI_araddr;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arprot <= redpitaya_axi_wrapper00_M00_AXI_arprot;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_arvalid <= redpitaya_axi_wrapper00_M00_AXI_arvalid;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awaddr <= redpitaya_axi_wrapper00_M00_AXI_awaddr;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awprot <= redpitaya_axi_wrapper00_M00_AXI_awprot;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_awvalid <= redpitaya_axi_wrapper00_M00_AXI_awvalid;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_bready <= redpitaya_axi_wrapper00_M00_AXI_bready;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_rready <= redpitaya_axi_wrapper00_M00_AXI_rready;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wdata <= redpitaya_axi_wrapper00_M00_AXI_wdata;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wstrb <= redpitaya_axi_wrapper00_M00_AXI_wstrb;
        redpitaya_axi_wrapper00_axim_intercon_redpitaya_axi_wrapper00_M00_AXI_wvalid <= redpitaya_axi_wrapper00_M00_AXI_wvalid;

    -- connect redpitaya_axi_wrapper00_candroutput_intercon
        -- analog_candrinput
        -- redpitaya_axi_wrapper00_candroutput
        redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_rst_o <= redpitaya_axi_wrapper00_rst_o;
        redpitaya_axi_wrapper00_candroutput_intercon_redpitaya_axi_wrapper00_clk_o <= redpitaya_axi_wrapper00_clk_o;

end architecture top_red_pseudogen_dds_1;
