# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/gwe/projets/oscimp/fpga_dev/redpitaya/red_pseudogen_dds/synthesis/red_pseudogen_dds.xdc

# Block Designs: bd/redpitaya_axi_wrapper_bd/redpitaya_axi_wrapper_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd || ORIG_REF_NAME==redpitaya_axi_wrapper_bd}]

# IP: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0}]

# IP: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_processing_system7_0_0/redpitaya_axi_wrapper_bd_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_0}]

# IP: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_processing_system7_0_axi_periph_0/redpitaya_axi_wrapper_bd_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_axi_periph_0}]

# IP: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_auto_pc_0/redpitaya_axi_wrapper_bd_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_auto_pc_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_auto_pc_0}]

# XDC: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0/redpitaya_axi_wrapper_bd_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_processing_system7_0_0/redpitaya_axi_wrapper_bd_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_0 || ORIG_REF_NAME==redpitaya_axi_wrapper_bd_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/redpitaya_axi_wrapper_bd/ip/redpitaya_axi_wrapper_bd_auto_pc_0/redpitaya_axi_wrapper_bd_auto_pc_0_ooc.xdc

# XDC: bd/redpitaya_axi_wrapper_bd/redpitaya_axi_wrapper_bd_ooc.xdc
