# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# Block Designs: bd/iq_demod_only_wrapper/iq_demod_only_wrapper.bd
# Block Designs: The module: 'iq_demod_only_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_ad9767_0_0/iq_demod_only_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_ad9767_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_ad9767_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_add_const_0_0/iq_demod_only_wrapper_add_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_add_const_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_add_const_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_add_const_2_0/iq_demod_only_wrapper_add_const_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_add_const_2_0 || ORIG_REF_NAME==iq_demod_only_wrapper_add_const_2_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_add_const_3_0/iq_demod_only_wrapper_add_const_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_add_const_3_0 || ORIG_REF_NAME==iq_demod_only_wrapper_add_const_3_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_ltc2145_0_0/iq_demod_only_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_ltc2145_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_ltc2145_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_mixer_sin_0_0/iq_demod_only_wrapper_mixer_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_mixer_sin_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_mixer_sin_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_nco_counter_0_0/iq_demod_only_wrapper_nco_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_nco_counter_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_nco_counter_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_nco_counter_1_0/iq_demod_only_wrapper_nco_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_nco_counter_1_0 || ORIG_REF_NAME==iq_demod_only_wrapper_nco_counter_1_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_proc_sys_reset_0_0/iq_demod_only_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_proc_sys_reset_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_processing_system7_0_0/iq_demod_only_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_processing_system7_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_processing_system7_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_ps7_0_axi_periph_0/iq_demod_only_wrapper_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_ps7_0_axi_periph_0 || ORIG_REF_NAME==iq_demod_only_wrapper_ps7_0_axi_periph_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xbar_0/iq_demod_only_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_xbar_0 || ORIG_REF_NAME==iq_demod_only_wrapper_xbar_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_redpitaya_adc_dac_clk_0_0/iq_demod_only_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_twoInMult_0_0/iq_demod_only_wrapper_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_twoInMult_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_twoInMult_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xlconstant_0_0/iq_demod_only_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_xlconstant_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_xlconstant_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xlslice_0_0/iq_demod_only_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_xlslice_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_xlslice_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_fir16RealbitsOneInTwoMult_v1_0_0_0/iq_demod_only_wrapper_fir16RealbitsOneInTwoMult_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_fir16RealbitsOneInTwoMult_v1_0_0_0 || ORIG_REF_NAME==iq_demod_only_wrapper_fir16RealbitsOneInTwoMult_v1_0_0_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xlslice_0_1/iq_demod_only_wrapper_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_xlslice_0_1 || ORIG_REF_NAME==iq_demod_only_wrapper_xlslice_0_1}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_0/iq_demod_only_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_0 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_0}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_1/iq_demod_only_wrapper_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_1 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_1}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_2/iq_demod_only_wrapper_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_2 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_2}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_3/iq_demod_only_wrapper_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_3 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_3}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_4/iq_demod_only_wrapper_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_4 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_4}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_5/iq_demod_only_wrapper_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_5 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_5}]

# IP: bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_auto_pc_6/iq_demod_only_wrapper_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==iq_demod_only_wrapper_auto_pc_6 || ORIG_REF_NAME==iq_demod_only_wrapper_auto_pc_6}]

# XDC: bd/iq_demod_only_wrapper/iq_demod_only_wrapper_ooc.xdc
