---------------------------------------------------------------------------
-- Company     : Automaticaly generated by POD
-- Author(s)   : $tpl:author$
--
-- Creation Date : 2016-09-13
-- File          : redpitaya_axi_wrapper00_candroutput.vhd
--
-- Abstract :
-- Connect slaves to candroutput from redpitaya_axi_wrapper00
--
---------------------------------------------------------------------------

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.numeric_std.all;

Entity redpitaya_axi_wrapper00_candroutput is
    port
    (

        -- analog_candrinput connection
        analog_clk_i                             : out  std_logic;
        analog_adc_rst_i                         : out  std_logic;

        -- redpitaya_axi_wrapper00_candroutput connection
        redpitaya_axi_wrapper00_rst_o            : in   std_logic;
        redpitaya_axi_wrapper00_clk_o            : in   std_logic
    );
end entity;

architecture redpitaya_axi_wrapper00_candroutput_1 of redpitaya_axi_wrapper00_candroutput is
begin

    -- Clock and Reset connection

    -- for analog
    analog_adc_rst_i <= redpitaya_axi_wrapper00_rst_o;
    analog_clk_i <= redpitaya_axi_wrapper00_clk_o;

end architecture redpitaya_axi_wrapper00_candroutput_1;
