# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters_adc.xdc

# XDC: /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters.xdc

# XDC: /home/bma/git/fpga_design/redpitaya/double_dds/design/pwm_axi_test.xdc

# Block Designs: bd/double_dds/double_dds.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds || ORIG_REF_NAME==double_dds} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_ps7_0/double_dds_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_ps7_0 || ORIG_REF_NAME==double_dds_ps7_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_ps7_rst_0/double_dds_ps7_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_ps7_rst_0 || ORIG_REF_NAME==double_dds_ps7_rst_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_redpitaya_converters_0_0/double_dds_redpitaya_converters_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_redpitaya_converters_0_0 || ORIG_REF_NAME==double_dds_redpitaya_converters_0_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_dds_ampl_0/double_dds_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_dds_ampl_0 || ORIG_REF_NAME==double_dds_dds_ampl_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_xbar_0/double_dds_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_xbar_0 || ORIG_REF_NAME==double_dds_xbar_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_auto_pc_0/double_dds_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_auto_pc_0 || ORIG_REF_NAME==double_dds_auto_pc_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_ps7_axi_0/double_dds_ps7_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_ps7_axi_0 || ORIG_REF_NAME==double_dds_ps7_axi_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_nco_counter_1_0/double_dds_nco_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_nco_counter_1_0 || ORIG_REF_NAME==double_dds_nco_counter_1_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_conv_nco_counter_1_0/double_dds_conv_nco_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_conv_nco_counter_1_0 || ORIG_REF_NAME==double_dds_conv_nco_counter_1_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_shifter_nco_counter_1_0/double_dds_shifter_nco_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_shifter_nco_counter_1_0 || ORIG_REF_NAME==double_dds_shifter_nco_counter_1_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_expander_nco_counter_1_0/double_dds_expander_nco_counter_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_expander_nco_counter_1_0 || ORIG_REF_NAME==double_dds_expander_nco_counter_1_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_nco_counter_2_0/double_dds_nco_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_nco_counter_2_0 || ORIG_REF_NAME==double_dds_nco_counter_2_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_conv_nco_counter_2_0/double_dds_conv_nco_counter_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_conv_nco_counter_2_0 || ORIG_REF_NAME==double_dds_conv_nco_counter_2_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_mixer_sin_1_0/double_dds_mixer_sin_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_mixer_sin_1_0 || ORIG_REF_NAME==double_dds_mixer_sin_1_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_mixer_sin_2_0/double_dds_mixer_sin_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_mixer_sin_2_0 || ORIG_REF_NAME==double_dds_mixer_sin_2_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_dds1_offset_0/double_dds_dds1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_dds1_offset_0 || ORIG_REF_NAME==double_dds_dds1_offset_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_dds2_offset_0/double_dds_dds2_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_dds2_offset_0 || ORIG_REF_NAME==double_dds_dds2_offset_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_adc1_offset_0/double_dds_adc1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_adc1_offset_0 || ORIG_REF_NAME==double_dds_adc1_offset_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_adc2_offset_0/double_dds_adc2_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_adc2_offset_0 || ORIG_REF_NAME==double_dds_adc2_offset_0} -quiet] -quiet

# IP: bd/double_dds/ip/double_dds_dataReal_to_ram_1_0/double_dds_dataReal_to_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_dds_dataReal_to_ram_1_0 || ORIG_REF_NAME==double_dds_dataReal_to_ram_1_0} -quiet] -quiet

# XDC: bd/double_dds/double_dds_ooc.xdc
