# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.cache/wt [current_project]
set_property parent.project_path /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/bma/git/github/oscimpDigital/fpga_ip [current_project]
update_ip_catalog
set_property ip_output_repo /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property verilog_define TOOL_VIVADO [current_fileset]
read_verilog -library xil_defaultlib /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/hdl/double_dds_wrapper.v
add_files /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/double_dds.bd
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_ps7_0/double_dds_ps7_0.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_ps7_rst_0/double_dds_ps7_rst_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_ps7_rst_0/double_dds_ps7_rst_0.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_ps7_rst_0/double_dds_ps7_rst_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_redpitaya_converters_0_0/redpitaya_converters_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_dds_ampl_0/axi_to_dac.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_xbar_0/double_dds_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_auto_pc_0/double_dds_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_nco_counter_1_0/nco_counter.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_nco_counter_2_0/nco_counter.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_dds1_offset_0/add_constReal.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_dds2_offset_0/add_constReal.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_adc1_offset_0/add_constReal.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_adc2_offset_0/add_constReal.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/ip/double_dds_dataReal_to_ram_1_0/dataReal_to_ram.xdc]
set_property used_in_implementation false [get_files -all /home/bma/git/fpga_design/redpitaya/double_dds/design/tmp/double_dds.srcs/sources_1/bd/double_dds/double_dds_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters_adc.xdc
set_property used_in_implementation false [get_files /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters_adc.xdc]

read_xdc /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters.xdc
set_property used_in_implementation false [get_files /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters.xdc]

read_xdc /home/bma/git/fpga_design/redpitaya/double_dds/design/pwm_axi_test.xdc
set_property used_in_implementation false [get_files /home/bma/git/fpga_design/redpitaya/double_dds/design/pwm_axi_test.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top double_dds_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef double_dds_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file double_dds_wrapper_utilization_synth.rpt -pb double_dds_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
