set_property PACKAGE_PIN M14 [get_ports spi_0_ss1_o]
set_property PACKAGE_PIN K16 [get_ports spi_0_sck_io]
set_property PACKAGE_PIN L14 [get_ports spi_0_io1_io]
set_property PACKAGE_PIN L16 [get_ports spi_0_io0_io]
set_property PACKAGE_PIN M15 [get_ports spi_0_ss_io]
set_property PACKAGE_PIN J16 [get_ports spi_0_ss2_o]

set_property IOSTANDARD LVCMOS33 [get_ports spi_0_ss1_o]
set_property IOSTANDARD LVCMOS33 [get_ports spi_0_sck_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_0_ss_io]
set_property IOSTANDARD LVCMOS33 [get_ports spi_0_ss2_o]