# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_1_0/double_iq_pid_vco_shifterReal_dyn_1_0.xci
# IP: The module: 'double_iq_pid_vco_shifterReal_dyn_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_1_0/shifterReal_dyn.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_iq_pid_vco_shifterReal_dyn_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/bma/git/fpga_design/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_1_0/double_iq_pid_vco_shifterReal_dyn_1_0.xci
# IP: The module: 'double_iq_pid_vco_shifterReal_dyn_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_1_0/shifterReal_dyn.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_iq_pid_vco_shifterReal_dyn_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
