# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/gain_only_wrapper/gain_only_wrapper.bd
# Block Designs: The module: 'gain_only_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_ad9767_0_0/gain_only_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_ad9767_0_0 || ORIG_REF_NAME==gain_only_wrapper_ad9767_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_axi_interconnect_0_0/gain_only_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==gain_only_wrapper_axi_interconnect_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_xbar_0/gain_only_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_xbar_0 || ORIG_REF_NAME==gain_only_wrapper_xbar_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_ampl_0/gain_only_wrapper_dds1_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds1_ampl_0 || ORIG_REF_NAME==gain_only_wrapper_dds1_ampl_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_offset_0/gain_only_wrapper_dds1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds1_offset_0 || ORIG_REF_NAME==gain_only_wrapper_dds1_offset_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_twoInMult_0_0/gain_only_wrapper_dds1_twoInMult_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds1_twoInMult_0_0 || ORIG_REF_NAME==gain_only_wrapper_dds1_twoInMult_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds2_ampl_0/gain_only_wrapper_dds2_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds2_ampl_0 || ORIG_REF_NAME==gain_only_wrapper_dds2_ampl_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds2_nco_counter_0/gain_only_wrapper_dds2_nco_counter_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds2_nco_counter_0 || ORIG_REF_NAME==gain_only_wrapper_dds2_nco_counter_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds2_offset_0/gain_only_wrapper_dds2_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds2_offset_0 || ORIG_REF_NAME==gain_only_wrapper_dds2_offset_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds2_phase_0/gain_only_wrapper_dds2_phase_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds2_phase_0 || ORIG_REF_NAME==gain_only_wrapper_dds2_phase_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_dds2_twoInMult_1_0/gain_only_wrapper_dds2_twoInMult_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_dds2_twoInMult_1_0 || ORIG_REF_NAME==gain_only_wrapper_dds2_twoInMult_1_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_ltc2145_0_0/gain_only_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_ltc2145_0_0 || ORIG_REF_NAME==gain_only_wrapper_ltc2145_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_proc_sys_reset_0_0/gain_only_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==gain_only_wrapper_proc_sys_reset_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_processing_system7_0_0/gain_only_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_processing_system7_0_0 || ORIG_REF_NAME==gain_only_wrapper_processing_system7_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_redpitaya_adc_dac_clk_0_0/gain_only_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==gain_only_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_xlconstant_0_0/gain_only_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_xlconstant_0_0 || ORIG_REF_NAME==gain_only_wrapper_xlconstant_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_xlconstant_1_0/gain_only_wrapper_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_xlconstant_1_0 || ORIG_REF_NAME==gain_only_wrapper_xlconstant_1_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_xlslice_0_0/gain_only_wrapper_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_xlslice_0_0 || ORIG_REF_NAME==gain_only_wrapper_xlslice_0_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_xlslice_1_0/gain_only_wrapper_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_xlslice_1_0 || ORIG_REF_NAME==gain_only_wrapper_xlslice_1_0}]

# IP: bd/gain_only_wrapper/ip/gain_only_wrapper_auto_pc_0/gain_only_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gain_only_wrapper_auto_pc_0 || ORIG_REF_NAME==gain_only_wrapper_auto_pc_0}]

# XDC: bd/gain_only_wrapper/gain_only_wrapper_ooc.xdc
