# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/iq_pid_vco/iq_pid_vco.srcs/sources_1/bd/iq_pid_vco_wrapper/ip/iq_pid_vco_wrapper_adc1_offset_0/iq_pid_vco_wrapper_adc1_offset_0.xci
# IP: The module: 'iq_pid_vco_wrapper_adc1_offset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/iq_pid_vco/iq_pid_vco.srcs/sources_1/bd/iq_pid_vco_wrapper/ip/iq_pid_vco_wrapper_adc1_offset_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_pid_vco_wrapper_adc1_offset_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/bma/git/fpga_design/redpitaya/iq_pid_vco/iq_pid_vco.srcs/sources_1/bd/iq_pid_vco_wrapper/ip/iq_pid_vco_wrapper_adc1_offset_0/iq_pid_vco_wrapper_adc1_offset_0.xci
# IP: The module: 'iq_pid_vco_wrapper_adc1_offset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/iq_pid_vco/iq_pid_vco.srcs/sources_1/bd/iq_pid_vco_wrapper/ip/iq_pid_vco_wrapper_adc1_offset_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_pid_vco_wrapper_adc1_offset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
