# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/adc_dac_clk_ooc.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/gpio.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/spi.xdc

# Block Designs: bd/test_pound_fironly_v1/test_pound_fironly_v1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1 || ORIG_REF_NAME==test_pound_fironly_v1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_processing_system7_0_0/test_pound_fironly_v1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_processing_system7_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_processing_system7_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_processing_system7_0_axi_periph_0/test_pound_fironly_v1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==test_pound_fironly_v1_processing_system7_0_axi_periph_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_rst_processing_system7_0_125M_0/test_pound_fironly_v1_rst_processing_system7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0/test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_ltc2145_0_0/test_pound_fironly_v1_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_ltc2145_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_ltc2145_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_ad9767_0_1/test_pound_fironly_v1_ad9767_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_ad9767_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_ad9767_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_xbar_0/test_pound_fironly_v1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_xbar_0 || ORIG_REF_NAME==test_pound_fironly_v1_xbar_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_axi_gpio_0_2/test_pound_fironly_v1_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_axi_gpio_0_2}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_fir16RealbitsOneInTwoMult_v1_0_0_2/test_pound_fironly_v1_fir16RealbitsOneInTwoMult_v1_0_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_fir16RealbitsOneInTwoMult_v1_0_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_fir16RealbitsOneInTwoMult_v1_0_0_2}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_shifterReal_0_2/test_pound_fironly_v1_shifterReal_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_shifterReal_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_shifterReal_0_2}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_mixer_sin_0_0/test_pound_fironly_v1_mixer_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_mixer_sin_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_mixer_sin_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_red_pitaya_pid_0_1/test_pound_fironly_v1_red_pitaya_pid_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_red_pitaya_pid_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_red_pitaya_pid_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_add_const_0_1/test_pound_fironly_v1_add_const_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_add_const_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_add_const_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_add_const_0_2/test_pound_fironly_v1_add_const_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_add_const_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_add_const_0_2}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_shifterReal_0_0/test_pound_fironly_v1_shifterReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_shifterReal_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_shifterReal_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_dupplReal_1_to_2_0_0/test_pound_fironly_v1_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_dupplReal_1_to_2_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_shifterReal_0_1/test_pound_fironly_v1_shifterReal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_shifterReal_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_shifterReal_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_dupplReal_1_to_2_0_3/test_pound_fironly_v1_dupplReal_1_to_2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_dupplReal_1_to_2_0_3 || ORIG_REF_NAME==test_pound_fironly_v1_dupplReal_1_to_2_0_3}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_moyenneurReal_0_0/test_pound_fironly_v1_moyenneurReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_moyenneurReal_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_moyenneurReal_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_moyenneurReal_0_1/test_pound_fironly_v1_moyenneurReal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_moyenneurReal_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_moyenneurReal_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_moyenneurReal_1_0/test_pound_fironly_v1_moyenneurReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_moyenneurReal_1_0 || ORIG_REF_NAME==test_pound_fironly_v1_moyenneurReal_1_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_data16_multi_to_ram_0_1/test_pound_fironly_v1_data16_multi_to_ram_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_data16_multi_to_ram_1_0/test_pound_fironly_v1_data16_multi_to_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_1_0 || ORIG_REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_1_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_nco_counter_0_0/test_pound_fironly_v1_nco_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_nco_counter_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_nco_counter_0_0}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_nco_counter_0_1/test_pound_fironly_v1_nco_counter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_nco_counter_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_nco_counter_0_1}]

# IP: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_auto_pc_0/test_pound_fironly_v1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_auto_pc_0 || ORIG_REF_NAME==test_pound_fironly_v1_auto_pc_0}]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_processing_system7_0_0/test_pound_fironly_v1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_processing_system7_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_rst_processing_system7_0_125M_0/test_pound_fironly_v1_rst_processing_system7_0_125M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_rst_processing_system7_0_125M_0/test_pound_fironly_v1_rst_processing_system7_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_fironly_v1_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_rst_processing_system7_0_125M_0/test_pound_fironly_v1_rst_processing_system7_0_125M_0_ooc.xdc

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_fironly_v1_redpitaya_adc_dac_clk_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_xbar_0/test_pound_fironly_v1_xbar_0_ooc.xdc

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_axi_gpio_0_2/test_pound_fironly_v1_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_axi_gpio_0_2/test_pound_fironly_v1_axi_gpio_0_2_ooc.xdc

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_axi_gpio_0_2/test_pound_fironly_v1_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_add_const_0_1/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_add_const_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_add_const_0_1}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_add_const_0_2/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_add_const_0_2 || ORIG_REF_NAME==test_pound_fironly_v1_add_const_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_data16_multi_to_ram_0_1/data16_multi_to_ram_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_0_1 || ORIG_REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_0_1}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_data16_multi_to_ram_1_0/data16_multi_to_ram_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_1_0 || ORIG_REF_NAME==test_pound_fironly_v1_data16_multi_to_ram_1_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_fironly_v1/ip/test_pound_fironly_v1_auto_pc_0/test_pound_fironly_v1_auto_pc_0_ooc.xdc

# XDC: bd/test_pound_fironly_v1/test_pound_fironly_v1_ooc.xdc
