# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/pid_vco_amp_mod_pid_only/pid_vco_amp_mod_pid_only.srcs/sources_1/bd/pid_vco_amp_mod_pid_only_wrapper/ip/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1.xci
# IP: The module: 'pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/pid_vco_amp_mod_pid_only/pid_vco_amp_mod_pid_only.srcs/sources_1/bd/pid_vco_amp_mod_pid_only_wrapper/ip/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/bma/git/fpga_design/redpitaya/pid_vco_amp_mod_pid_only/pid_vco_amp_mod_pid_only.srcs/sources_1/bd/pid_vco_amp_mod_pid_only_wrapper/ip/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1.xci
# IP: The module: 'pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/pid_vco_amp_mod_pid_only/pid_vco_amp_mod_pid_only.srcs/sources_1/bd/pid_vco_amp_mod_pid_only_wrapper/ip/pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pid_vco_amp_mod_pid_only_wrapper_pid2_kp_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
