set_false_path -from [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C] -to [get_pins wb_inst/readdata_s_reg[0]/D]
set_false_path -from [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C] -to [get_pins wb_inst/readdata_s_reg[0]/D]
set_false_path -from [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C] -to [get_pins wb_inst/readdata_s_reg[1]/D]
set_false_path -from [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C] -to [get_pins wb_inst/readdata_s_reg[2]/D]

#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[0]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[1]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[2]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[3]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[4]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[5]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[6]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[7]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[8]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[9]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[10]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[0].data_subtop_inst/acquisition_fsm_inst/counter_reg[11]/R]

#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[0]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[1]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[2]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[3]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[4]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[5]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[6]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[7]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[8]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[9]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[10]/R]
#set_false_path -from [get_ports s00_axi_reset] -to [get_pins data32_top_inst/subtop_loop[1].data_subtop_inst/acquisition_fsm_inst/counter_reg[11]/R]

#set_property shreg_extract no [get_cells -hier -filter {name =~ *rst_sync*}]
set_false_path -from [get_pins {data32_top_inst/subtop_loop[*].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C}] -to [get_pins {data32_top_inst/subtop_loop[*].data_subtop_inst/start_acquisition2_s_reg/D}]
set_false_path -from [get_pins {data32_top_inst/subtop_loop[*].data_subtop_inst/acquisition_fsm_inst/busy_s_reg/C}] -to [get_pins {wb_inst/readdata_s_reg[*]/D}]

