# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/adc_dac_clk_ooc.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/gpio.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/spi.xdc

# Block Designs: bd/test_pound_FIR/test_pound_FIR.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR || ORIG_REF_NAME==test_pound_FIR}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_processing_system7_0_0/test_pound_FIR_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_processing_system7_0_0 || ORIG_REF_NAME==test_pound_FIR_processing_system7_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_processing_system7_0_axi_periph_0/test_pound_FIR_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==test_pound_FIR_processing_system7_0_axi_periph_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_rst_processing_system7_0_125M_0/test_pound_FIR_rst_processing_system7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_redpitaya_adc_dac_clk_0_0/test_pound_FIR_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_FIR_redpitaya_adc_dac_clk_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_ltc2145_0_0/test_pound_FIR_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_ltc2145_0_0 || ORIG_REF_NAME==test_pound_FIR_ltc2145_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_ad9767_0_1/test_pound_FIR_ad9767_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_ad9767_0_1 || ORIG_REF_NAME==test_pound_FIR_ad9767_0_1}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_xbar_0/test_pound_FIR_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_xbar_0 || ORIG_REF_NAME==test_pound_FIR_xbar_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_axi_gpio_0_2/test_pound_FIR_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_FIR_axi_gpio_0_2}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_shifterReal_0_2/test_pound_FIR_shifterReal_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_shifterReal_0_2 || ORIG_REF_NAME==test_pound_FIR_shifterReal_0_2}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_add_const_0_1/test_pound_FIR_add_const_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_add_const_0_1 || ORIG_REF_NAME==test_pound_FIR_add_const_0_1}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_add_const_0_2/test_pound_FIR_add_const_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_add_const_0_2 || ORIG_REF_NAME==test_pound_FIR_add_const_0_2}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_nco_counter_0_0/test_pound_FIR_nco_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_nco_counter_0_0 || ORIG_REF_NAME==test_pound_FIR_nco_counter_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_mixer_sin_0_0/test_pound_FIR_mixer_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_mixer_sin_0_0 || ORIG_REF_NAME==test_pound_FIR_mixer_sin_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_fir16bitsOneInTwoMult_v1_0_0_0/test_pound_FIR_fir16bitsOneInTwoMult_v1_0_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_fir16bitsOneInTwoMult_v1_0_0_0 || ORIG_REF_NAME==test_pound_FIR_fir16bitsOneInTwoMult_v1_0_0_0}]

# IP: bd/test_pound_FIR/ip/test_pound_FIR_auto_pc_0/test_pound_FIR_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_FIR_auto_pc_0 || ORIG_REF_NAME==test_pound_FIR_auto_pc_0}]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_processing_system7_0_0/test_pound_FIR_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_processing_system7_0_0 || ORIG_REF_NAME==test_pound_FIR_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_rst_processing_system7_0_125M_0/test_pound_FIR_rst_processing_system7_0_125M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_rst_processing_system7_0_125M_0/test_pound_FIR_rst_processing_system7_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_FIR_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_rst_processing_system7_0_125M_0/test_pound_FIR_rst_processing_system7_0_125M_0_ooc.xdc

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_FIR_redpitaya_adc_dac_clk_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_xbar_0/test_pound_FIR_xbar_0_ooc.xdc

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_axi_gpio_0_2/test_pound_FIR_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_FIR_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_axi_gpio_0_2/test_pound_FIR_axi_gpio_0_2_ooc.xdc

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_axi_gpio_0_2/test_pound_FIR_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_FIR_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_add_const_0_1/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_add_const_0_1 || ORIG_REF_NAME==test_pound_FIR_add_const_0_1}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_add_const_0_2/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_FIR_add_const_0_2 || ORIG_REF_NAME==test_pound_FIR_add_const_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound_FIR/ip/test_pound_FIR_auto_pc_0/test_pound_FIR_auto_pc_0_ooc.xdc

# XDC: bd/test_pound_FIR/test_pound_FIR_ooc.xdc
