# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/dds_gnuradio/dds_gnuradio.srcs/sources_1/bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_1_0/dds_gnuradio_wrapper_add_const_1_0.xci
# IP: The module: 'dds_gnuradio_wrapper_add_const_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/dds_gnuradio/dds_gnuradio.srcs/sources_1/bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_1_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_gnuradio_wrapper_add_const_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/bma/git/fpga_design/redpitaya/dds_gnuradio/dds_gnuradio.srcs/sources_1/bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_1_0/dds_gnuradio_wrapper_add_const_1_0.xci
# IP: The module: 'dds_gnuradio_wrapper_add_const_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/dds_gnuradio/dds_gnuradio.srcs/sources_1/bd/dds_gnuradio_wrapper/ip/dds_gnuradio_wrapper_add_const_1_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dds_gnuradio_wrapper_add_const_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
