# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/gain_only/gain_only.srcs/sources_1/bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_offset_0/gain_only_wrapper_dds1_offset_0.xci
# IP: The module: 'gain_only_wrapper_dds1_offset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/gain_only/gain_only.srcs/sources_1/bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_offset_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gain_only_wrapper_dds1_offset_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/bma/git/fpga_design/redpitaya/gain_only/gain_only.srcs/sources_1/bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_offset_0/gain_only_wrapper_dds1_offset_0.xci
# IP: The module: 'gain_only_wrapper_dds1_offset_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/gain_only/gain_only.srcs/sources_1/bd/gain_only_wrapper/ip/gain_only_wrapper_dds1_offset_0/add_const_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gain_only_wrapper_dds1_offset_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
