# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# XDC: imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/adc_dac_clk_ooc.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/gpio.xdc

# XDC: imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/spi.xdc

# Block Designs: bd/test_pound/test_pound.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound || ORIG_REF_NAME==test_pound}]

# IP: bd/test_pound/ip/test_pound_processing_system7_0_0/test_pound_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_processing_system7_0_0 || ORIG_REF_NAME==test_pound_processing_system7_0_0}]

# IP: bd/test_pound/ip/test_pound_processing_system7_0_axi_periph_0/test_pound_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==test_pound_processing_system7_0_axi_periph_0}]

# IP: bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_rst_processing_system7_0_125M_0}]

# IP: bd/test_pound/ip/test_pound_redpitaya_adc_dac_clk_0_0/test_pound_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_redpitaya_adc_dac_clk_0_0}]

# IP: bd/test_pound/ip/test_pound_ltc2145_0_0/test_pound_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_ltc2145_0_0 || ORIG_REF_NAME==test_pound_ltc2145_0_0}]

# IP: bd/test_pound/ip/test_pound_ad9767_0_1/test_pound_ad9767_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_ad9767_0_1 || ORIG_REF_NAME==test_pound_ad9767_0_1}]

# IP: bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_axi_gpio_0_2}]

# IP: bd/test_pound/ip/test_pound_fir16RealbitsOneInTwoMult_v1_0_0_2/test_pound_fir16RealbitsOneInTwoMult_v1_0_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_fir16RealbitsOneInTwoMult_v1_0_0_2 || ORIG_REF_NAME==test_pound_fir16RealbitsOneInTwoMult_v1_0_0_2}]

# IP: bd/test_pound/ip/test_pound_shifterReal_0_2/test_pound_shifterReal_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_shifterReal_0_2 || ORIG_REF_NAME==test_pound_shifterReal_0_2}]

# IP: bd/test_pound/ip/test_pound_mixer_sin_0_0/test_pound_mixer_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_mixer_sin_0_0 || ORIG_REF_NAME==test_pound_mixer_sin_0_0}]

# IP: bd/test_pound/ip/test_pound_add_const_0_1/test_pound_add_const_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_0_1 || ORIG_REF_NAME==test_pound_add_const_0_1}]

# IP: bd/test_pound/ip/test_pound_add_const_0_2/test_pound_add_const_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_0_2 || ORIG_REF_NAME==test_pound_add_const_0_2}]

# IP: bd/test_pound/ip/test_pound_shifterReal_0_0/test_pound_shifterReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_shifterReal_0_0 || ORIG_REF_NAME==test_pound_shifterReal_0_0}]

# IP: bd/test_pound/ip/test_pound_dupplReal_1_to_2_0_0/test_pound_dupplReal_1_to_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_dupplReal_1_to_2_0_0 || ORIG_REF_NAME==test_pound_dupplReal_1_to_2_0_0}]

# IP: bd/test_pound/ip/test_pound_dupplReal_1_to_2_0_3/test_pound_dupplReal_1_to_2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_dupplReal_1_to_2_0_3 || ORIG_REF_NAME==test_pound_dupplReal_1_to_2_0_3}]

# IP: bd/test_pound/ip/test_pound_moyenneurReal_0_0/test_pound_moyenneurReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_moyenneurReal_0_0 || ORIG_REF_NAME==test_pound_moyenneurReal_0_0}]

# IP: bd/test_pound/ip/test_pound_moyenneurReal_0_1/test_pound_moyenneurReal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_moyenneurReal_0_1 || ORIG_REF_NAME==test_pound_moyenneurReal_0_1}]

# IP: bd/test_pound/ip/test_pound_moyenneurReal_1_0/test_pound_moyenneurReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_moyenneurReal_1_0 || ORIG_REF_NAME==test_pound_moyenneurReal_1_0}]

# IP: bd/test_pound/ip/test_pound_data16_multi_to_ram_1_0/test_pound_data16_multi_to_ram_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_data16_multi_to_ram_1_0 || ORIG_REF_NAME==test_pound_data16_multi_to_ram_1_0}]

# IP: bd/test_pound/ip/test_pound_nco_counter_0_0/test_pound_nco_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_nco_counter_0_0 || ORIG_REF_NAME==test_pound_nco_counter_0_0}]

# IP: bd/test_pound/ip/test_pound_nco_counter_0_1/test_pound_nco_counter_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_nco_counter_0_1 || ORIG_REF_NAME==test_pound_nco_counter_0_1}]

# IP: bd/test_pound/ip/test_pound_add_const_2_0/test_pound_add_const_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_2_0 || ORIG_REF_NAME==test_pound_add_const_2_0}]

# IP: bd/test_pound/ip/test_pound_shifterReal_3_0/test_pound_shifterReal_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_shifterReal_3_0 || ORIG_REF_NAME==test_pound_shifterReal_3_0}]

# IP: bd/test_pound/ip/test_pound_shifterReal_1_0/test_pound_shifterReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_shifterReal_1_0 || ORIG_REF_NAME==test_pound_shifterReal_1_0}]

# IP: bd/test_pound/ip/test_pound_expanderReal_0_0/test_pound_expanderReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_expanderReal_0_0 || ORIG_REF_NAME==test_pound_expanderReal_0_0}]

# IP: bd/test_pound/ip/test_pound_dupplReal_1_to_2_1_0/test_pound_dupplReal_1_to_2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_dupplReal_1_to_2_1_0 || ORIG_REF_NAME==test_pound_dupplReal_1_to_2_1_0}]

# IP: bd/test_pound/ip/test_pound_add_const_3_0/test_pound_add_const_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_3_0 || ORIG_REF_NAME==test_pound_add_const_3_0}]

# IP: bd/test_pound/ip/test_pound_add_const_4_0/test_pound_add_const_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_4_0 || ORIG_REF_NAME==test_pound_add_const_4_0}]

# IP: bd/test_pound/ip/test_pound_moyenneurReal_3_0/test_pound_moyenneurReal_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_moyenneurReal_3_0 || ORIG_REF_NAME==test_pound_moyenneurReal_3_0}]

# IP: bd/test_pound/ip/test_pound_dupplReal_1_to_2_2_0/test_pound_dupplReal_1_to_2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_dupplReal_1_to_2_2_0 || ORIG_REF_NAME==test_pound_dupplReal_1_to_2_2_0}]

# IP: bd/test_pound/ip/test_pound_add_const_5_0/test_pound_add_const_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_0 || ORIG_REF_NAME==test_pound_add_const_5_0}]

# IP: bd/test_pound/ip/test_pound_add_const_5_1/test_pound_add_const_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_1 || ORIG_REF_NAME==test_pound_add_const_5_1}]

# IP: bd/test_pound/ip/test_pound_add_const_5_2/test_pound_add_const_5_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_2 || ORIG_REF_NAME==test_pound_add_const_5_2}]

# IP: bd/test_pound/ip/test_pound_red_pitaya_pidv2_0_0/test_pound_red_pitaya_pidv2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_red_pitaya_pidv2_0_0 || ORIG_REF_NAME==test_pound_red_pitaya_pidv2_0_0}]

# IP: bd/test_pound/ip/test_pound_shifterReal_5_0/test_pound_shifterReal_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_shifterReal_5_0 || ORIG_REF_NAME==test_pound_shifterReal_5_0}]

# IP: bd/test_pound/ip/test_pound_data32Real_multi_to_ram_0_0/test_pound_data32Real_multi_to_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_data32Real_multi_to_ram_0_0 || ORIG_REF_NAME==test_pound_data32Real_multi_to_ram_0_0}]

# IP: bd/test_pound/ip/test_pound_limiteur_0_0/test_pound_limiteur_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_limiteur_0_0 || ORIG_REF_NAME==test_pound_limiteur_0_0}]

# IP: bd/test_pound/ip/test_pound_xbar_0/test_pound_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_xbar_0 || ORIG_REF_NAME==test_pound_xbar_0}]

# IP: bd/test_pound/ip/test_pound_auto_pc_0/test_pound_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_0 || ORIG_REF_NAME==test_pound_auto_pc_0}]

# IP: bd/test_pound/ip/test_pound_auto_pc_1/test_pound_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_1 || ORIG_REF_NAME==test_pound_auto_pc_1}]

# IP: bd/test_pound/ip/test_pound_auto_pc_2/test_pound_auto_pc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_2 || ORIG_REF_NAME==test_pound_auto_pc_2}]

# IP: bd/test_pound/ip/test_pound_auto_pc_3/test_pound_auto_pc_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_3 || ORIG_REF_NAME==test_pound_auto_pc_3}]

# IP: bd/test_pound/ip/test_pound_auto_pc_4/test_pound_auto_pc_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_4 || ORIG_REF_NAME==test_pound_auto_pc_4}]

# IP: bd/test_pound/ip/test_pound_auto_pc_5/test_pound_auto_pc_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_5 || ORIG_REF_NAME==test_pound_auto_pc_5}]

# IP: bd/test_pound/ip/test_pound_auto_pc_6/test_pound_auto_pc_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_6 || ORIG_REF_NAME==test_pound_auto_pc_6}]

# IP: bd/test_pound/ip/test_pound_auto_pc_7/test_pound_auto_pc_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_7 || ORIG_REF_NAME==test_pound_auto_pc_7}]

# IP: bd/test_pound/ip/test_pound_auto_pc_8/test_pound_auto_pc_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_8 || ORIG_REF_NAME==test_pound_auto_pc_8}]

# IP: bd/test_pound/ip/test_pound_auto_pc_9/test_pound_auto_pc_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_9 || ORIG_REF_NAME==test_pound_auto_pc_9}]

# IP: bd/test_pound/ip/test_pound_auto_pc_10/test_pound_auto_pc_10.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_10 || ORIG_REF_NAME==test_pound_auto_pc_10}]

# IP: bd/test_pound/ip/test_pound_auto_pc_11/test_pound_auto_pc_11.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_11 || ORIG_REF_NAME==test_pound_auto_pc_11}]

# IP: bd/test_pound/ip/test_pound_auto_pc_12/test_pound_auto_pc_12.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_12 || ORIG_REF_NAME==test_pound_auto_pc_12}]

# IP: bd/test_pound/ip/test_pound_auto_pc_13/test_pound_auto_pc_13.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_13 || ORIG_REF_NAME==test_pound_auto_pc_13}]

# IP: bd/test_pound/ip/test_pound_auto_pc_14/test_pound_auto_pc_14.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_14 || ORIG_REF_NAME==test_pound_auto_pc_14}]

# IP: bd/test_pound/ip/test_pound_auto_pc_15/test_pound_auto_pc_15.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==test_pound_auto_pc_15 || ORIG_REF_NAME==test_pound_auto_pc_15}]

# XDC: bd/test_pound/ip/test_pound_processing_system7_0_0/test_pound_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_processing_system7_0_0 || ORIG_REF_NAME==test_pound_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_rst_processing_system7_0_125M_0 || ORIG_REF_NAME==test_pound_rst_processing_system7_0_125M_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==test_pound_redpitaya_adc_dac_clk_0_0}] {/inst }]/inst ]]

# XDC: bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_axi_gpio_0_2 || ORIG_REF_NAME==test_pound_axi_gpio_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_0_1/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_0_1 || ORIG_REF_NAME==test_pound_add_const_0_1}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_0_2/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_0_2 || ORIG_REF_NAME==test_pound_add_const_0_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_data16_multi_to_ram_1_0/data16_multi_to_ram_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_data16_multi_to_ram_1_0 || ORIG_REF_NAME==test_pound_data16_multi_to_ram_1_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_2_0/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_2_0 || ORIG_REF_NAME==test_pound_add_const_2_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_3_0/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_3_0 || ORIG_REF_NAME==test_pound_add_const_3_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_4_0/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_4_0 || ORIG_REF_NAME==test_pound_add_const_4_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_5_0/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_0 || ORIG_REF_NAME==test_pound_add_const_5_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_5_1/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_1 || ORIG_REF_NAME==test_pound_add_const_5_1}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_add_const_5_2/add_const_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_add_const_5_2 || ORIG_REF_NAME==test_pound_add_const_5_2}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_data32Real_multi_to_ram_0_0/data32Real_ooc.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==test_pound_data32Real_multi_to_ram_0_0 || ORIG_REF_NAME==test_pound_data32Real_multi_to_ram_0_0}] {/U0 }]/U0 ]]

# XDC: bd/test_pound/ip/test_pound_xbar_0/test_pound_xbar_0_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_0/test_pound_auto_pc_0_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_1/test_pound_auto_pc_1_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_2/test_pound_auto_pc_2_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_3/test_pound_auto_pc_3_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_4/test_pound_auto_pc_4_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_5/test_pound_auto_pc_5_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_6/test_pound_auto_pc_6_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_7/test_pound_auto_pc_7_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_8/test_pound_auto_pc_8_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_9/test_pound_auto_pc_9_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_10/test_pound_auto_pc_10_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_11/test_pound_auto_pc_11_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_12/test_pound_auto_pc_12_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_13/test_pound_auto_pc_13_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_14/test_pound_auto_pc_14_ooc.xdc

# XDC: bd/test_pound/ip/test_pound_auto_pc_15/test_pound_auto_pc_15_ooc.xdc

# XDC: bd/test_pound/test_pound_ooc.xdc
