# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.cache/wt [current_project]
set_property parent.project_path /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:redpitaya:part0:1.0 [current_project]
set_property ip_repo_paths /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/gitlab/oimp/fpga_ip [current_project]
set_property ip_cache_permissions disable [current_project]
read_verilog -library xil_defaultlib /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/hdl/test_pound_wrapper.v
add_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/test_pound.bd
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_processing_system7_0_0/test_pound_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_rst_processing_system7_0_125M_0/test_pound_rst_processing_system7_0_125M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_redpitaya_adc_dac_clk_0_0/adc_dac_clk_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_axi_gpio_0_2/test_pound_axi_gpio_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_0_1/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_0_2/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_data16_multi_to_ram_1_0/data16_multi_to_ram_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_2_0/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_3_0/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_4_0/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_5_0/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_5_1/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_add_const_5_2/add_const_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_data32Real_multi_to_ram_0_0/data32Real_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_xbar_0/test_pound_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_0/test_pound_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_1/test_pound_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_2/test_pound_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_3/test_pound_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_4/test_pound_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_5/test_pound_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_6/test_pound_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_7/test_pound_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_8/test_pound_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_9/test_pound_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_10/test_pound_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_11/test_pound_auto_pc_11_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_12/test_pound_auto_pc_12_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_13/test_pound_auto_pc_13_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_14/test_pound_auto_pc_14_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/ip/test_pound_auto_pc_15/test_pound_auto_pc_15_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/test_pound_ooc.xdc]
set_property is_locked true [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/sources_1/bd/test_pound/test_pound.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/ad9767/ad9767.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/ad9767/ad9767.xdc]

read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/ltc2145/ltc2145-redpy.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/ltc2145/ltc2145-redpy.xdc]

read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc]

read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/adc_dac_clk_ooc.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/ome/pyb/git/oimp/fpga_ip/redpitaya_adc_dac_clk/adc_dac_clk_ooc.xdc]

read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/gpio.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/gpio.xdc]

read_xdc /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/spi.xdc
set_property used_in_implementation false [get_files /home/bma/Documents/BPT_sync/Work/5-ED_SPIM/Work/git/fpga_design/redpitaya/test_pound/test_pound.srcs/constrs_1/imports/av-sys/louloulou/redpitaya2/prog/test_pyb_from_2015-11-05_phaseManip/fpga2015/fpga2015/fpga2015.srcs/constrs_1/new/spi.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top test_pound_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef test_pound_wrapper.dcp

catch { report_utilization -file test_pound_wrapper_utilization_synth.rpt -pb test_pound_wrapper_utilization_synth.pb }
