# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/fpga_design/redpitaya/iq_demod_only/iq_demod_only.srcs/sources_1/bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xbar_0/iq_demod_only_wrapper_xbar_0.xci
# IP: The module: 'iq_demod_only_wrapper_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/iq_demod_only/iq_demod_only.srcs/sources_1/bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xbar_0/iq_demod_only_wrapper_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_demod_only_wrapper_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/bma/git/fpga_design/redpitaya/iq_demod_only/iq_demod_only.srcs/sources_1/bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xbar_0/iq_demod_only_wrapper_xbar_0.xci
# IP: The module: 'iq_demod_only_wrapper_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/fpga_design/redpitaya/iq_demod_only/iq_demod_only.srcs/sources_1/bd/iq_demod_only_wrapper/ip/iq_demod_only_wrapper_xbar_0/iq_demod_only_wrapper_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'iq_demod_only_wrapper_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
