# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/bma/git/github/oscimpDigital/app/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_ampl_0/double_iq_pid_vco_dds_ampl_0.xci
# IP: The module: 'double_iq_pid_vco_dds_ampl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/github/oscimpDigital/app/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_ampl_0/axi_to_dac.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_iq_pid_vco_dds_ampl_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/bma/git/github/oscimpDigital/app/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_ampl_0/double_iq_pid_vco_dds_ampl_0.xci
# IP: The module: 'double_iq_pid_vco_dds_ampl_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/bma/git/github/oscimpDigital/app/redpitaya/double_iq_pid_vco/design/tmp/double_iq_pid_vco.srcs/sources_1/bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_ampl_0/axi_to_dac.xdc
# XDC: The top module name and the constraint reference have the same name: 'double_iq_pid_vco_dds_ampl_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
