BASE_NAME=adc_fft
CORE_MODULES_LIST = \
	${OSCIMP_DIGITAL_DRIVER}/data_to_ram_core/data_to_ram_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/data_to_ram_core/data_to_ram_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/fft_core/fft_core.ko \
	${OSCIMP_DIGITAL_DRIVER}/fir_core/fir_core.ko
include $(OSCIMP_DIGITAL_APP)/Makefile.inc
