# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/fpga_ip/ad9767/ad9767.xdc

# XDC: imports/fpga_ip/ltc2145/ltc2145-redpy.xdc

# XDC: imports/fpga_ip/redpitaya_adc_dac_clk/redpitaya_clk_pin.xdc

# Block Designs: bd/pid_only_wrapper/pid_only_wrapper.bd
# Block Designs: The module: 'pid_only_wrapper' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_proc_sys_reset_0_0/pid_only_wrapper_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_proc_sys_reset_0_0 || ORIG_REF_NAME==pid_only_wrapper_proc_sys_reset_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_axi_interconnect_0_0/pid_only_wrapper_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_axi_interconnect_0_0 || ORIG_REF_NAME==pid_only_wrapper_axi_interconnect_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_xbar_0/pid_only_wrapper_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_xbar_0 || ORIG_REF_NAME==pid_only_wrapper_xbar_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_processing_system7_0_0/pid_only_wrapper_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_processing_system7_0_0 || ORIG_REF_NAME==pid_only_wrapper_processing_system7_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_redpitaya_adc_dac_clk_0_0/pid_only_wrapper_redpitaya_adc_dac_clk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_redpitaya_adc_dac_clk_0_0 || ORIG_REF_NAME==pid_only_wrapper_redpitaya_adc_dac_clk_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_ltc2145_0_0/pid_only_wrapper_ltc2145_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_ltc2145_0_0 || ORIG_REF_NAME==pid_only_wrapper_ltc2145_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_ad9767_0_0/pid_only_wrapper_ad9767_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_ad9767_0_0 || ORIG_REF_NAME==pid_only_wrapper_ad9767_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_0_0/pid_only_wrapper_add_const_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_0_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_0_3/pid_only_wrapper_add_const_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_0_3 || ORIG_REF_NAME==pid_only_wrapper_add_const_0_3}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_red_pitaya_pidv3_0_0/pid_only_wrapper_red_pitaya_pidv3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_red_pitaya_pidv3_0_0 || ORIG_REF_NAME==pid_only_wrapper_red_pitaya_pidv3_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_0_1/pid_only_wrapper_add_const_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_0_1 || ORIG_REF_NAME==pid_only_wrapper_add_const_0_1}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_xlconstant_0_0/pid_only_wrapper_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_xlconstant_0_0 || ORIG_REF_NAME==pid_only_wrapper_xlconstant_0_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_2_0/pid_only_wrapper_add_const_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_2_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_2_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_3_0/pid_only_wrapper_add_const_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_3_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_3_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_4_0/pid_only_wrapper_add_const_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_4_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_4_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_5_0/pid_only_wrapper_add_const_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_5_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_5_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_add_const_6_0/pid_only_wrapper_add_const_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_add_const_6_0 || ORIG_REF_NAME==pid_only_wrapper_add_const_6_0}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_xlconstant_0_1/pid_only_wrapper_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_xlconstant_0_1 || ORIG_REF_NAME==pid_only_wrapper_xlconstant_0_1}]

# IP: bd/pid_only_wrapper/ip/pid_only_wrapper_auto_pc_0/pid_only_wrapper_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pid_only_wrapper_auto_pc_0 || ORIG_REF_NAME==pid_only_wrapper_auto_pc_0}]

# XDC: bd/pid_only_wrapper/pid_only_wrapper_ooc.xdc
