# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters_adc.xdc

# XDC: /home/bma/git/github/oscimpDigital/fpga_ip/redpitaya_converters/redpitaya_converters.xdc

# Block Designs: bd/double_iq_pid_vco/double_iq_pid_vco.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco || ORIG_REF_NAME==double_iq_pid_vco} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_ps7_0/double_iq_pid_vco_ps7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_ps7_0 || ORIG_REF_NAME==double_iq_pid_vco_ps7_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_ps7_rst_0/double_iq_pid_vco_ps7_rst_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_ps7_rst_0 || ORIG_REF_NAME==double_iq_pid_vco_ps7_rst_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_redpitaya_converters_0_0/double_iq_pid_vco_redpitaya_converters_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_redpitaya_converters_0_0 || ORIG_REF_NAME==double_iq_pid_vco_redpitaya_converters_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_adc1_offset_0/double_iq_pid_vco_adc1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_adc1_offset_0 || ORIG_REF_NAME==double_iq_pid_vco_adc1_offset_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_xbar_0/double_iq_pid_vco_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_xbar_0 || ORIG_REF_NAME==double_iq_pid_vco_xbar_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_ps7_axi_0/double_iq_pid_vco_ps7_axi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_ps7_axi_0 || ORIG_REF_NAME==double_iq_pid_vco_ps7_axi_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_adc2_offset_0/double_iq_pid_vco_adc2_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_adc2_offset_0 || ORIG_REF_NAME==double_iq_pid_vco_adc2_offset_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_convertComplexToReal_0_0/double_iq_pid_vco_convertComplexToReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_convertComplexToReal_0_0 || ORIG_REF_NAME==double_iq_pid_vco_convertComplexToReal_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_convertComplexToReal_1_0/double_iq_pid_vco_convertComplexToReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_convertComplexToReal_1_0 || ORIG_REF_NAME==double_iq_pid_vco_convertComplexToReal_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_convertComplexToReal_4_0/double_iq_pid_vco_convertComplexToReal_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_convertComplexToReal_4_0 || ORIG_REF_NAME==double_iq_pid_vco_convertComplexToReal_4_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_convertComplexToReal_5_0/double_iq_pid_vco_convertComplexToReal_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_convertComplexToReal_5_0 || ORIG_REF_NAME==double_iq_pid_vco_convertComplexToReal_5_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dataReal_to_ram_fast_0/double_iq_pid_vco_dataReal_to_ram_fast_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dataReal_to_ram_fast_0 || ORIG_REF_NAME==double_iq_pid_vco_dataReal_to_ram_fast_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dataReal_to_ram_slow_0/double_iq_pid_vco_dataReal_to_ram_slow_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dataReal_to_ram_slow_0 || ORIG_REF_NAME==double_iq_pid_vco_dataReal_to_ram_slow_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds1_f0_0/double_iq_pid_vco_dds1_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds1_f0_0 || ORIG_REF_NAME==double_iq_pid_vco_dds1_f0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds1_nco_0/double_iq_pid_vco_dds1_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds1_nco_0 || ORIG_REF_NAME==double_iq_pid_vco_dds1_nco_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds1_offset_0/double_iq_pid_vco_dds1_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds1_offset_0 || ORIG_REF_NAME==double_iq_pid_vco_dds1_offset_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds2_f0_0/double_iq_pid_vco_dds2_f0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds2_f0_0 || ORIG_REF_NAME==double_iq_pid_vco_dds2_f0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds2_nco_0/double_iq_pid_vco_dds2_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds2_nco_0 || ORIG_REF_NAME==double_iq_pid_vco_dds2_nco_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds2_offset_0/double_iq_pid_vco_dds2_offset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds2_offset_0 || ORIG_REF_NAME==double_iq_pid_vco_dds2_offset_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_ampl_0/double_iq_pid_vco_dds_ampl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds_ampl_0 || ORIG_REF_NAME==double_iq_pid_vco_dds_ampl_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dds_range_0/double_iq_pid_vco_dds_range_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dds_range_0 || ORIG_REF_NAME==double_iq_pid_vco_dds_range_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_demod1_nco_0/double_iq_pid_vco_demod1_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_demod1_nco_0 || ORIG_REF_NAME==double_iq_pid_vco_demod1_nco_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_demod2_nco_0/double_iq_pid_vco_demod2_nco_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_demod2_nco_0 || ORIG_REF_NAME==double_iq_pid_vco_demod2_nco_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_expanderReal_2_0/double_iq_pid_vco_expanderReal_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_expanderReal_2_0 || ORIG_REF_NAME==double_iq_pid_vco_expanderReal_2_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_expanderReal_3_0/double_iq_pid_vco_expanderReal_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_expanderReal_3_0 || ORIG_REF_NAME==double_iq_pid_vco_expanderReal_3_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_firReal_0_0/double_iq_pid_vco_firReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_firReal_0_0 || ORIG_REF_NAME==double_iq_pid_vco_firReal_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_firReal_1_0/double_iq_pid_vco_firReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_firReal_1_0 || ORIG_REF_NAME==double_iq_pid_vco_firReal_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_meanReal_0_0/double_iq_pid_vco_meanReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_meanReal_0_0 || ORIG_REF_NAME==double_iq_pid_vco_meanReal_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_meanReal_1_0/double_iq_pid_vco_meanReal_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_meanReal_1_0 || ORIG_REF_NAME==double_iq_pid_vco_meanReal_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_meanReal_2_0/double_iq_pid_vco_meanReal_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_meanReal_2_0 || ORIG_REF_NAME==double_iq_pid_vco_meanReal_2_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_meanReal_3_0/double_iq_pid_vco_meanReal_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_meanReal_3_0 || ORIG_REF_NAME==double_iq_pid_vco_meanReal_3_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_0_0/double_iq_pid_vco_mixer_sin_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_0_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_1_0/double_iq_pid_vco_mixer_sin_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_1_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_2_0/double_iq_pid_vco_mixer_sin_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_2_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_2_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_3_0/double_iq_pid_vco_mixer_sin_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_3_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_3_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_4_0/double_iq_pid_vco_mixer_sin_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_4_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_4_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_mixer_sin_5_0/double_iq_pid_vco_mixer_sin_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_mixer_sin_5_0 || ORIG_REF_NAME==double_iq_pid_vco_mixer_sin_5_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_pidv3_axi_0_0/double_iq_pid_vco_pidv3_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_pidv3_axi_0_0 || ORIG_REF_NAME==double_iq_pid_vco_pidv3_axi_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_pidv3_axi_1_0/double_iq_pid_vco_pidv3_axi_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_pidv3_axi_1_0 || ORIG_REF_NAME==double_iq_pid_vco_pidv3_axi_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_2_0/double_iq_pid_vco_shifterReal_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_shifterReal_2_0 || ORIG_REF_NAME==double_iq_pid_vco_shifterReal_2_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_3_0/double_iq_pid_vco_shifterReal_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_shifterReal_3_0 || ORIG_REF_NAME==double_iq_pid_vco_shifterReal_3_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_0_0/double_iq_pid_vco_shifterReal_dyn_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_shifterReal_dyn_0_0 || ORIG_REF_NAME==double_iq_pid_vco_shifterReal_dyn_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_shifterReal_dyn_1_0/double_iq_pid_vco_shifterReal_dyn_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_shifterReal_dyn_1_0 || ORIG_REF_NAME==double_iq_pid_vco_shifterReal_dyn_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dupplReal_0_0/double_iq_pid_vco_dupplReal_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dupplReal_0_0 || ORIG_REF_NAME==double_iq_pid_vco_dupplReal_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_dupplReal_0_1/double_iq_pid_vco_dupplReal_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_dupplReal_0_1 || ORIG_REF_NAME==double_iq_pid_vco_dupplReal_0_1} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_tier2_xbar_0_0/double_iq_pid_vco_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_tier2_xbar_0_0 || ORIG_REF_NAME==double_iq_pid_vco_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_tier2_xbar_1_0/double_iq_pid_vco_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_tier2_xbar_1_0 || ORIG_REF_NAME==double_iq_pid_vco_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_tier2_xbar_2_0/double_iq_pid_vco_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_tier2_xbar_2_0 || ORIG_REF_NAME==double_iq_pid_vco_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/double_iq_pid_vco/ip/double_iq_pid_vco_auto_pc_0/double_iq_pid_vco_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==double_iq_pid_vco_auto_pc_0 || ORIG_REF_NAME==double_iq_pid_vco_auto_pc_0} -quiet] -quiet

# XDC: bd/double_iq_pid_vco/double_iq_pid_vco_ooc.xdc
